## This file is a general .xdc for the Nexys A7-100T
## To use it in a project:
## - uncomment the lines corresponding to used pins
## - rename the used ports (in each line, after get_ports) according to the top level signal names in the project

## Clock signal
set_property -dict {PACKAGE_PIN E3 IOSTANDARD LVCMOS33} [get_ports clk]
#create_clock -period 10.000 -name sys_clk_pin -waveform {0.000 5.000} -add [get_ports clk]


##Switches

set_property -dict { PACKAGE_PIN J15   IOSTANDARD LVCMOS33 } [get_ports { sw[0] }]; #IO_L24N_T3_RS0_15 Sch=sw[0]
set_property -dict { PACKAGE_PIN L16   IOSTANDARD LVCMOS33 } [get_ports { sw[1] }]; #IO_L3N_T0_DQS_EMCCLK_14 Sch=sw[1]
set_property -dict { PACKAGE_PIN M13   IOSTANDARD LVCMOS33 } [get_ports { SW[2] }]; #IO_L6N_T0_D08_VREF_14 Sch=sw[2]
set_property -dict { PACKAGE_PIN R15   IOSTANDARD LVCMOS33 } [get_ports { SW[3] }]; #IO_L13N_T2_MRCC_14 Sch=sw[3]
set_property -dict { PACKAGE_PIN R17   IOSTANDARD LVCMOS33 } [get_ports { SW[4] }]; #IO_L12N_T1_MRCC_14 Sch=sw[4]
set_property -dict { PACKAGE_PIN T18   IOSTANDARD LVCMOS33 } [get_ports { SW[5] }]; #IO_L7N_T1_D10_14 Sch=sw[5]
set_property -dict { PACKAGE_PIN U18   IOSTANDARD LVCMOS33 } [get_ports { SW[6] }]; #IO_L17N_T2_A13_D29_14 Sch=sw[6]
set_property -dict { PACKAGE_PIN R13   IOSTANDARD LVCMOS33 } [get_ports { SW[7] }]; #IO_L5N_T0_D07_14 Sch=sw[7]
set_property -dict { PACKAGE_PIN T8    IOSTANDARD LVCMOS18 } [get_ports { SW[8] }]; #IO_L24N_T3_34 Sch=sw[8]
set_property -dict { PACKAGE_PIN U8    IOSTANDARD LVCMOS18 } [get_ports { SW[9] }]; #IO_25_34 Sch=sw[9]
set_property -dict { PACKAGE_PIN R16   IOSTANDARD LVCMOS33 } [get_ports { SW[10] }]; #IO_L15P_T2_DQS_RDWR_B_14 Sch=sw[10]
set_property -dict { PACKAGE_PIN T13   IOSTANDARD LVCMOS33 } [get_ports { SW[11] }]; #IO_L23P_T3_A03_D19_14 Sch=sw[11]
set_property -dict { PACKAGE_PIN H6    IOSTANDARD LVCMOS33 } [get_ports { SW[12] }]; #IO_L24P_T3_35 Sch=sw[12]
set_property -dict { PACKAGE_PIN U12   IOSTANDARD LVCMOS33 } [get_ports { SW[13] }]; #IO_L20P_T3_A08_D24_14 Sch=sw[13]
set_property -dict { PACKAGE_PIN U11   IOSTANDARD LVCMOS33 } [get_ports { SW[14] }]; #IO_L19N_T3_A09_D25_VREF_14 Sch=sw[14]
set_property -dict { PACKAGE_PIN V10   IOSTANDARD LVCMOS33 } [get_ports { SW[15] }]; #IO_L21P_T3_DQS_14 Sch=sw[15]


## LEDs

set_property -dict {PACKAGE_PIN H17 IOSTANDARD LVCMOS33} [get_ports led0]
#set_property -dict { PACKAGE_PIN K15   IOSTANDARD LVCMOS33 } [get_ports { led1 }]; #IO_L24P_T3_RS1_15 Sch=led[1]
#set_property -dict { PACKAGE_PIN J13   IOSTANDARD LVCMOS33 } [get_ports { led[2] }]; #IO_L17N_T2_A25_15 Sch=led[2]
#set_property -dict { PACKAGE_PIN N14   IOSTANDARD LVCMOS33 } [get_ports { led[3] }]; #IO_L8P_T1_D11_14 Sch=led[3]
#set_property -dict { PACKAGE_PIN R18   IOSTANDARD LVCMOS33 } [get_ports { led[4] }]; #IO_L7P_T1_D09_14 Sch=led[4]
#set_property -dict { PACKAGE_PIN V17   IOSTANDARD LVCMOS33 } [get_ports { led[5] }]; #IO_L18N_T2_A11_D27_14 Sch=led[5]
#set_property -dict { PACKAGE_PIN U17   IOSTANDARD LVCMOS33 } [get_ports { led[6] }]; #IO_L17P_T2_A14_D30_14 Sch=led[6]
#set_property -dict { PACKAGE_PIN U16   IOSTANDARD LVCMOS33 } [get_ports { led[7] }]; #IO_L18P_T2_A12_D28_14 Sch=led[7]
#set_property -dict { PACKAGE_PIN V16   IOSTANDARD LVCMOS33 } [get_ports { led[8] }]; #IO_L16N_T2_A15_D31_14 Sch=led[8]
#set_property -dict { PACKAGE_PIN T15   IOSTANDARD LVCMOS33 } [get_ports { led[9] }]; #IO_L14N_T2_SRCC_14 Sch=led[9]
#set_property -dict { PACKAGE_PIN U14   IOSTANDARD LVCMOS33 } [get_ports { led[10] }]; #IO_L22P_T3_A05_D21_14 Sch=led[10]
#set_property -dict { PACKAGE_PIN T16   IOSTANDARD LVCMOS33 } [get_ports { led[11] }]; #IO_L15N_T2_DQS_DOUT_CSO_B_14 Sch=led[11]
#set_property -dict { PACKAGE_PIN V15   IOSTANDARD LVCMOS33 } [get_ports { led[12] }]; #IO_L16P_T2_CSI_B_14 Sch=led[12]
#set_property -dict { PACKAGE_PIN V14   IOSTANDARD LVCMOS33 } [get_ports { led[13] }]; #IO_L22N_T3_A04_D20_14 Sch=led[13]
#set_property -dict { PACKAGE_PIN V12   IOSTANDARD LVCMOS33 } [get_ports { led[14] }]; #IO_L20N_T3_A07_D23_14 Sch=led[14]
#set_property -dict { PACKAGE_PIN V11   IOSTANDARD LVCMOS33 } [get_ports { led[15] }]; #IO_L21N_T3_DQS_A06_D22_14 Sch=led[15]

#set_property -dict { PACKAGE_PIN R12   IOSTANDARD LVCMOS33 } [get_ports { RGB1_Blue }]; #IO_L5P_T0_D06_14 Sch=led16_b
#set_property -dict { PACKAGE_PIN M16   IOSTANDARD LVCMOS33 } [get_ports { RGB1_Green }]; #IO_L10P_T1_D14_14 Sch=led16_g
#set_property -dict { PACKAGE_PIN N15   IOSTANDARD LVCMOS33 } [get_ports { RGB1_Red }]; #IO_L11P_T1_SRCC_14 Sch=led16_r
#set_property -dict { PACKAGE_PIN G14   IOSTANDARD LVCMOS33 } [get_ports { RGB2_Blue }]; #IO_L15N_T2_DQS_ADV_B_15 Sch=led17_b
#set_property -dict { PACKAGE_PIN R11   IOSTANDARD LVCMOS33 } [get_ports { RGB2_Green }]; #IO_0_14 Sch=led17_g
#set_property -dict { PACKAGE_PIN N16   IOSTANDARD LVCMOS33 } [get_ports { RGB2_Red }]; #IO_L11N_T1_SRCC_14 Sch=led17_r


##7 segment display

set_property -dict {PACKAGE_PIN T10 IOSTANDARD LVCMOS33} [get_ports {seg[0]}]
set_property -dict {PACKAGE_PIN R10 IOSTANDARD LVCMOS33} [get_ports {seg[1]}]
set_property -dict {PACKAGE_PIN K16 IOSTANDARD LVCMOS33} [get_ports {seg[2]}]
set_property -dict {PACKAGE_PIN K13 IOSTANDARD LVCMOS33} [get_ports {seg[3]}]
set_property -dict {PACKAGE_PIN P15 IOSTANDARD LVCMOS33} [get_ports {seg[4]}]
set_property -dict {PACKAGE_PIN T11 IOSTANDARD LVCMOS33} [get_ports {seg[5]}]
set_property -dict {PACKAGE_PIN L18 IOSTANDARD LVCMOS33} [get_ports {seg[6]}]
set_property -dict {PACKAGE_PIN H15 IOSTANDARD LVCMOS33} [get_ports dp]

set_property -dict {PACKAGE_PIN J17 IOSTANDARD LVCMOS33} [get_ports {SSEG_AN[0]}]
set_property -dict {PACKAGE_PIN J18 IOSTANDARD LVCMOS33} [get_ports {SSEG_AN[1]}]
set_property -dict {PACKAGE_PIN T9 IOSTANDARD LVCMOS33} [get_ports {SSEG_AN[2]}]
set_property -dict {PACKAGE_PIN J14 IOSTANDARD LVCMOS33} [get_ports {SSEG_AN[3]}]
set_property -dict {PACKAGE_PIN P14 IOSTANDARD LVCMOS33} [get_ports {SSEG_AN[4]}]
set_property -dict {PACKAGE_PIN T14 IOSTANDARD LVCMOS33} [get_ports {SSEG_AN[5]}]
set_property -dict {PACKAGE_PIN K2 IOSTANDARD LVCMOS33} [get_ports {SSEG_AN[6]}]
set_property -dict {PACKAGE_PIN U13 IOSTANDARD LVCMOS33} [get_ports {SSEG_AN[7]}]


##Buttons

#cpu_resetn
#set_property -dict { PACKAGE_PIN C12   IOSTANDARD LVCMOS33 } [get_ports { CPU_RESETN }];

#btnc
#set_property -dict { PACKAGE_PIN N17   IOSTANDARD LVCMOS33 } [get_ports { BTN[4] }];

#btn_up
set_property -dict {PACKAGE_PIN M18 IOSTANDARD LVCMOS33} [get_ports reset]

#btn_left
#set_property -dict { PACKAGE_PIN P17   IOSTANDARD LVCMOS33 } [get_ports { w_btn }];

#btn_right
set_property -dict {PACKAGE_PIN M17 IOSTANDARD LVCMOS33} [get_ports start_btn]

#btn_down
set_property -dict {PACKAGE_PIN P18 IOSTANDARD LVCMOS33} [get_ports step_btn]


# below is about the debug core ILA, not important

create_debug_core u_ila_0 ila
set_property ALL_PROBE_SAME_MU true [get_debug_cores u_ila_0]
set_property ALL_PROBE_SAME_MU_CNT 1 [get_debug_cores u_ila_0]
set_property C_ADV_TRIGGER false [get_debug_cores u_ila_0]
set_property C_DATA_DEPTH 1024 [get_debug_cores u_ila_0]
set_property C_EN_STRG_QUAL false [get_debug_cores u_ila_0]
set_property C_INPUT_PIPE_STAGES 0 [get_debug_cores u_ila_0]
set_property C_TRIGIN_EN false [get_debug_cores u_ila_0]
set_property C_TRIGOUT_EN false [get_debug_cores u_ila_0]
set_property port_width 1 [get_debug_ports u_ila_0/clk]
connect_debug_port u_ila_0/clk [get_nets [list wiz/inst/clk_out1]]
set_property PROBE_TYPE DATA_AND_TRIGGER [get_debug_ports u_ila_0/probe0]
set_property port_width 32 [get_debug_ports u_ila_0/probe0]
connect_debug_port u_ila_0/probe0 [get_nets [list {core_instantiation/mips_i/dp/rf/rf[10]__0[0]} {core_instantiation/mips_i/dp/rf/rf[10]__0[1]} {core_instantiation/mips_i/dp/rf/rf[10]__0[2]} {core_instantiation/mips_i/dp/rf/rf[10]__0[3]} {core_instantiation/mips_i/dp/rf/rf[10]__0[4]} {core_instantiation/mips_i/dp/rf/rf[10]__0[5]} {core_instantiation/mips_i/dp/rf/rf[10]__0[6]} {core_instantiation/mips_i/dp/rf/rf[10]__0[7]} {core_instantiation/mips_i/dp/rf/rf[10]__0[8]} {core_instantiation/mips_i/dp/rf/rf[10]__0[9]} {core_instantiation/mips_i/dp/rf/rf[10]__0[10]} {core_instantiation/mips_i/dp/rf/rf[10]__0[11]} {core_instantiation/mips_i/dp/rf/rf[10]__0[12]} {core_instantiation/mips_i/dp/rf/rf[10]__0[13]} {core_instantiation/mips_i/dp/rf/rf[10]__0[14]} {core_instantiation/mips_i/dp/rf/rf[10]__0[15]} {core_instantiation/mips_i/dp/rf/rf[10]__0[16]} {core_instantiation/mips_i/dp/rf/rf[10]__0[17]} {core_instantiation/mips_i/dp/rf/rf[10]__0[18]} {core_instantiation/mips_i/dp/rf/rf[10]__0[19]} {core_instantiation/mips_i/dp/rf/rf[10]__0[20]} {core_instantiation/mips_i/dp/rf/rf[10]__0[21]} {core_instantiation/mips_i/dp/rf/rf[10]__0[22]} {core_instantiation/mips_i/dp/rf/rf[10]__0[23]} {core_instantiation/mips_i/dp/rf/rf[10]__0[24]} {core_instantiation/mips_i/dp/rf/rf[10]__0[25]} {core_instantiation/mips_i/dp/rf/rf[10]__0[26]} {core_instantiation/mips_i/dp/rf/rf[10]__0[27]} {core_instantiation/mips_i/dp/rf/rf[10]__0[28]} {core_instantiation/mips_i/dp/rf/rf[10]__0[29]} {core_instantiation/mips_i/dp/rf/rf[10]__0[30]} {core_instantiation/mips_i/dp/rf/rf[10]__0[31]}]]
create_debug_port u_ila_0 probe
set_property PROBE_TYPE DATA_AND_TRIGGER [get_debug_ports u_ila_0/probe1]
set_property port_width 32 [get_debug_ports u_ila_0/probe1]
connect_debug_port u_ila_0/probe1 [get_nets [list {core_instantiation/mips_i/dp/rf/rf[11]__0[0]} {core_instantiation/mips_i/dp/rf/rf[11]__0[1]} {core_instantiation/mips_i/dp/rf/rf[11]__0[2]} {core_instantiation/mips_i/dp/rf/rf[11]__0[3]} {core_instantiation/mips_i/dp/rf/rf[11]__0[4]} {core_instantiation/mips_i/dp/rf/rf[11]__0[5]} {core_instantiation/mips_i/dp/rf/rf[11]__0[6]} {core_instantiation/mips_i/dp/rf/rf[11]__0[7]} {core_instantiation/mips_i/dp/rf/rf[11]__0[8]} {core_instantiation/mips_i/dp/rf/rf[11]__0[9]} {core_instantiation/mips_i/dp/rf/rf[11]__0[10]} {core_instantiation/mips_i/dp/rf/rf[11]__0[11]} {core_instantiation/mips_i/dp/rf/rf[11]__0[12]} {core_instantiation/mips_i/dp/rf/rf[11]__0[13]} {core_instantiation/mips_i/dp/rf/rf[11]__0[14]} {core_instantiation/mips_i/dp/rf/rf[11]__0[15]} {core_instantiation/mips_i/dp/rf/rf[11]__0[16]} {core_instantiation/mips_i/dp/rf/rf[11]__0[17]} {core_instantiation/mips_i/dp/rf/rf[11]__0[18]} {core_instantiation/mips_i/dp/rf/rf[11]__0[19]} {core_instantiation/mips_i/dp/rf/rf[11]__0[20]} {core_instantiation/mips_i/dp/rf/rf[11]__0[21]} {core_instantiation/mips_i/dp/rf/rf[11]__0[22]} {core_instantiation/mips_i/dp/rf/rf[11]__0[23]} {core_instantiation/mips_i/dp/rf/rf[11]__0[24]} {core_instantiation/mips_i/dp/rf/rf[11]__0[25]} {core_instantiation/mips_i/dp/rf/rf[11]__0[26]} {core_instantiation/mips_i/dp/rf/rf[11]__0[27]} {core_instantiation/mips_i/dp/rf/rf[11]__0[28]} {core_instantiation/mips_i/dp/rf/rf[11]__0[29]} {core_instantiation/mips_i/dp/rf/rf[11]__0[30]} {core_instantiation/mips_i/dp/rf/rf[11]__0[31]}]]
create_debug_port u_ila_0 probe
set_property PROBE_TYPE DATA_AND_TRIGGER [get_debug_ports u_ila_0/probe2]
set_property port_width 32 [get_debug_ports u_ila_0/probe2]
connect_debug_port u_ila_0/probe2 [get_nets [list {core_instantiation/mips_i/dp/rf/rf[13]__0[0]} {core_instantiation/mips_i/dp/rf/rf[13]__0[1]} {core_instantiation/mips_i/dp/rf/rf[13]__0[2]} {core_instantiation/mips_i/dp/rf/rf[13]__0[3]} {core_instantiation/mips_i/dp/rf/rf[13]__0[4]} {core_instantiation/mips_i/dp/rf/rf[13]__0[5]} {core_instantiation/mips_i/dp/rf/rf[13]__0[6]} {core_instantiation/mips_i/dp/rf/rf[13]__0[7]} {core_instantiation/mips_i/dp/rf/rf[13]__0[8]} {core_instantiation/mips_i/dp/rf/rf[13]__0[9]} {core_instantiation/mips_i/dp/rf/rf[13]__0[10]} {core_instantiation/mips_i/dp/rf/rf[13]__0[11]} {core_instantiation/mips_i/dp/rf/rf[13]__0[12]} {core_instantiation/mips_i/dp/rf/rf[13]__0[13]} {core_instantiation/mips_i/dp/rf/rf[13]__0[14]} {core_instantiation/mips_i/dp/rf/rf[13]__0[15]} {core_instantiation/mips_i/dp/rf/rf[13]__0[16]} {core_instantiation/mips_i/dp/rf/rf[13]__0[17]} {core_instantiation/mips_i/dp/rf/rf[13]__0[18]} {core_instantiation/mips_i/dp/rf/rf[13]__0[19]} {core_instantiation/mips_i/dp/rf/rf[13]__0[20]} {core_instantiation/mips_i/dp/rf/rf[13]__0[21]} {core_instantiation/mips_i/dp/rf/rf[13]__0[22]} {core_instantiation/mips_i/dp/rf/rf[13]__0[23]} {core_instantiation/mips_i/dp/rf/rf[13]__0[24]} {core_instantiation/mips_i/dp/rf/rf[13]__0[25]} {core_instantiation/mips_i/dp/rf/rf[13]__0[26]} {core_instantiation/mips_i/dp/rf/rf[13]__0[27]} {core_instantiation/mips_i/dp/rf/rf[13]__0[28]} {core_instantiation/mips_i/dp/rf/rf[13]__0[29]} {core_instantiation/mips_i/dp/rf/rf[13]__0[30]} {core_instantiation/mips_i/dp/rf/rf[13]__0[31]}]]
create_debug_port u_ila_0 probe
set_property PROBE_TYPE DATA_AND_TRIGGER [get_debug_ports u_ila_0/probe3]
set_property port_width 32 [get_debug_ports u_ila_0/probe3]
connect_debug_port u_ila_0/probe3 [get_nets [list {core_instantiation/mips_i/dp/rf/rf[16]__0[0]} {core_instantiation/mips_i/dp/rf/rf[16]__0[1]} {core_instantiation/mips_i/dp/rf/rf[16]__0[2]} {core_instantiation/mips_i/dp/rf/rf[16]__0[3]} {core_instantiation/mips_i/dp/rf/rf[16]__0[4]} {core_instantiation/mips_i/dp/rf/rf[16]__0[5]} {core_instantiation/mips_i/dp/rf/rf[16]__0[6]} {core_instantiation/mips_i/dp/rf/rf[16]__0[7]} {core_instantiation/mips_i/dp/rf/rf[16]__0[8]} {core_instantiation/mips_i/dp/rf/rf[16]__0[9]} {core_instantiation/mips_i/dp/rf/rf[16]__0[10]} {core_instantiation/mips_i/dp/rf/rf[16]__0[11]} {core_instantiation/mips_i/dp/rf/rf[16]__0[12]} {core_instantiation/mips_i/dp/rf/rf[16]__0[13]} {core_instantiation/mips_i/dp/rf/rf[16]__0[14]} {core_instantiation/mips_i/dp/rf/rf[16]__0[15]} {core_instantiation/mips_i/dp/rf/rf[16]__0[16]} {core_instantiation/mips_i/dp/rf/rf[16]__0[17]} {core_instantiation/mips_i/dp/rf/rf[16]__0[18]} {core_instantiation/mips_i/dp/rf/rf[16]__0[19]} {core_instantiation/mips_i/dp/rf/rf[16]__0[20]} {core_instantiation/mips_i/dp/rf/rf[16]__0[21]} {core_instantiation/mips_i/dp/rf/rf[16]__0[22]} {core_instantiation/mips_i/dp/rf/rf[16]__0[23]} {core_instantiation/mips_i/dp/rf/rf[16]__0[24]} {core_instantiation/mips_i/dp/rf/rf[16]__0[25]} {core_instantiation/mips_i/dp/rf/rf[16]__0[26]} {core_instantiation/mips_i/dp/rf/rf[16]__0[27]} {core_instantiation/mips_i/dp/rf/rf[16]__0[28]} {core_instantiation/mips_i/dp/rf/rf[16]__0[29]} {core_instantiation/mips_i/dp/rf/rf[16]__0[30]} {core_instantiation/mips_i/dp/rf/rf[16]__0[31]}]]
create_debug_port u_ila_0 probe
set_property PROBE_TYPE DATA_AND_TRIGGER [get_debug_ports u_ila_0/probe4]
set_property port_width 32 [get_debug_ports u_ila_0/probe4]
connect_debug_port u_ila_0/probe4 [get_nets [list {core_instantiation/mips_i/dp/rf/rf[17]__0[0]} {core_instantiation/mips_i/dp/rf/rf[17]__0[1]} {core_instantiation/mips_i/dp/rf/rf[17]__0[2]} {core_instantiation/mips_i/dp/rf/rf[17]__0[3]} {core_instantiation/mips_i/dp/rf/rf[17]__0[4]} {core_instantiation/mips_i/dp/rf/rf[17]__0[5]} {core_instantiation/mips_i/dp/rf/rf[17]__0[6]} {core_instantiation/mips_i/dp/rf/rf[17]__0[7]} {core_instantiation/mips_i/dp/rf/rf[17]__0[8]} {core_instantiation/mips_i/dp/rf/rf[17]__0[9]} {core_instantiation/mips_i/dp/rf/rf[17]__0[10]} {core_instantiation/mips_i/dp/rf/rf[17]__0[11]} {core_instantiation/mips_i/dp/rf/rf[17]__0[12]} {core_instantiation/mips_i/dp/rf/rf[17]__0[13]} {core_instantiation/mips_i/dp/rf/rf[17]__0[14]} {core_instantiation/mips_i/dp/rf/rf[17]__0[15]} {core_instantiation/mips_i/dp/rf/rf[17]__0[16]} {core_instantiation/mips_i/dp/rf/rf[17]__0[17]} {core_instantiation/mips_i/dp/rf/rf[17]__0[18]} {core_instantiation/mips_i/dp/rf/rf[17]__0[19]} {core_instantiation/mips_i/dp/rf/rf[17]__0[20]} {core_instantiation/mips_i/dp/rf/rf[17]__0[21]} {core_instantiation/mips_i/dp/rf/rf[17]__0[22]} {core_instantiation/mips_i/dp/rf/rf[17]__0[23]} {core_instantiation/mips_i/dp/rf/rf[17]__0[24]} {core_instantiation/mips_i/dp/rf/rf[17]__0[25]} {core_instantiation/mips_i/dp/rf/rf[17]__0[26]} {core_instantiation/mips_i/dp/rf/rf[17]__0[27]} {core_instantiation/mips_i/dp/rf/rf[17]__0[28]} {core_instantiation/mips_i/dp/rf/rf[17]__0[29]} {core_instantiation/mips_i/dp/rf/rf[17]__0[30]} {core_instantiation/mips_i/dp/rf/rf[17]__0[31]}]]
create_debug_port u_ila_0 probe
set_property PROBE_TYPE DATA_AND_TRIGGER [get_debug_ports u_ila_0/probe5]
set_property port_width 32 [get_debug_ports u_ila_0/probe5]
connect_debug_port u_ila_0/probe5 [get_nets [list {core_instantiation/mips_i/dp/rf/rf[0]__0[0]} {core_instantiation/mips_i/dp/rf/rf[0]__0[1]} {core_instantiation/mips_i/dp/rf/rf[0]__0[2]} {core_instantiation/mips_i/dp/rf/rf[0]__0[3]} {core_instantiation/mips_i/dp/rf/rf[0]__0[4]} {core_instantiation/mips_i/dp/rf/rf[0]__0[5]} {core_instantiation/mips_i/dp/rf/rf[0]__0[6]} {core_instantiation/mips_i/dp/rf/rf[0]__0[7]} {core_instantiation/mips_i/dp/rf/rf[0]__0[8]} {core_instantiation/mips_i/dp/rf/rf[0]__0[9]} {core_instantiation/mips_i/dp/rf/rf[0]__0[10]} {core_instantiation/mips_i/dp/rf/rf[0]__0[11]} {core_instantiation/mips_i/dp/rf/rf[0]__0[12]} {core_instantiation/mips_i/dp/rf/rf[0]__0[13]} {core_instantiation/mips_i/dp/rf/rf[0]__0[14]} {core_instantiation/mips_i/dp/rf/rf[0]__0[15]} {core_instantiation/mips_i/dp/rf/rf[0]__0[16]} {core_instantiation/mips_i/dp/rf/rf[0]__0[17]} {core_instantiation/mips_i/dp/rf/rf[0]__0[18]} {core_instantiation/mips_i/dp/rf/rf[0]__0[19]} {core_instantiation/mips_i/dp/rf/rf[0]__0[20]} {core_instantiation/mips_i/dp/rf/rf[0]__0[21]} {core_instantiation/mips_i/dp/rf/rf[0]__0[22]} {core_instantiation/mips_i/dp/rf/rf[0]__0[23]} {core_instantiation/mips_i/dp/rf/rf[0]__0[24]} {core_instantiation/mips_i/dp/rf/rf[0]__0[25]} {core_instantiation/mips_i/dp/rf/rf[0]__0[26]} {core_instantiation/mips_i/dp/rf/rf[0]__0[27]} {core_instantiation/mips_i/dp/rf/rf[0]__0[28]} {core_instantiation/mips_i/dp/rf/rf[0]__0[29]} {core_instantiation/mips_i/dp/rf/rf[0]__0[30]} {core_instantiation/mips_i/dp/rf/rf[0]__0[31]}]]
create_debug_port u_ila_0 probe
set_property PROBE_TYPE DATA_AND_TRIGGER [get_debug_ports u_ila_0/probe6]
set_property port_width 32 [get_debug_ports u_ila_0/probe6]
connect_debug_port u_ila_0/probe6 [get_nets [list {core_instantiation/mips_i/dp/rf/rf[12]__0[0]} {core_instantiation/mips_i/dp/rf/rf[12]__0[1]} {core_instantiation/mips_i/dp/rf/rf[12]__0[2]} {core_instantiation/mips_i/dp/rf/rf[12]__0[3]} {core_instantiation/mips_i/dp/rf/rf[12]__0[4]} {core_instantiation/mips_i/dp/rf/rf[12]__0[5]} {core_instantiation/mips_i/dp/rf/rf[12]__0[6]} {core_instantiation/mips_i/dp/rf/rf[12]__0[7]} {core_instantiation/mips_i/dp/rf/rf[12]__0[8]} {core_instantiation/mips_i/dp/rf/rf[12]__0[9]} {core_instantiation/mips_i/dp/rf/rf[12]__0[10]} {core_instantiation/mips_i/dp/rf/rf[12]__0[11]} {core_instantiation/mips_i/dp/rf/rf[12]__0[12]} {core_instantiation/mips_i/dp/rf/rf[12]__0[13]} {core_instantiation/mips_i/dp/rf/rf[12]__0[14]} {core_instantiation/mips_i/dp/rf/rf[12]__0[15]} {core_instantiation/mips_i/dp/rf/rf[12]__0[16]} {core_instantiation/mips_i/dp/rf/rf[12]__0[17]} {core_instantiation/mips_i/dp/rf/rf[12]__0[18]} {core_instantiation/mips_i/dp/rf/rf[12]__0[19]} {core_instantiation/mips_i/dp/rf/rf[12]__0[20]} {core_instantiation/mips_i/dp/rf/rf[12]__0[21]} {core_instantiation/mips_i/dp/rf/rf[12]__0[22]} {core_instantiation/mips_i/dp/rf/rf[12]__0[23]} {core_instantiation/mips_i/dp/rf/rf[12]__0[24]} {core_instantiation/mips_i/dp/rf/rf[12]__0[25]} {core_instantiation/mips_i/dp/rf/rf[12]__0[26]} {core_instantiation/mips_i/dp/rf/rf[12]__0[27]} {core_instantiation/mips_i/dp/rf/rf[12]__0[28]} {core_instantiation/mips_i/dp/rf/rf[12]__0[29]} {core_instantiation/mips_i/dp/rf/rf[12]__0[30]} {core_instantiation/mips_i/dp/rf/rf[12]__0[31]}]]
create_debug_port u_ila_0 probe
set_property PROBE_TYPE DATA_AND_TRIGGER [get_debug_ports u_ila_0/probe7]
set_property port_width 32 [get_debug_ports u_ila_0/probe7]
connect_debug_port u_ila_0/probe7 [get_nets [list {core_instantiation/mips_i/dp/rf/rf[14]__0[0]} {core_instantiation/mips_i/dp/rf/rf[14]__0[1]} {core_instantiation/mips_i/dp/rf/rf[14]__0[2]} {core_instantiation/mips_i/dp/rf/rf[14]__0[3]} {core_instantiation/mips_i/dp/rf/rf[14]__0[4]} {core_instantiation/mips_i/dp/rf/rf[14]__0[5]} {core_instantiation/mips_i/dp/rf/rf[14]__0[6]} {core_instantiation/mips_i/dp/rf/rf[14]__0[7]} {core_instantiation/mips_i/dp/rf/rf[14]__0[8]} {core_instantiation/mips_i/dp/rf/rf[14]__0[9]} {core_instantiation/mips_i/dp/rf/rf[14]__0[10]} {core_instantiation/mips_i/dp/rf/rf[14]__0[11]} {core_instantiation/mips_i/dp/rf/rf[14]__0[12]} {core_instantiation/mips_i/dp/rf/rf[14]__0[13]} {core_instantiation/mips_i/dp/rf/rf[14]__0[14]} {core_instantiation/mips_i/dp/rf/rf[14]__0[15]} {core_instantiation/mips_i/dp/rf/rf[14]__0[16]} {core_instantiation/mips_i/dp/rf/rf[14]__0[17]} {core_instantiation/mips_i/dp/rf/rf[14]__0[18]} {core_instantiation/mips_i/dp/rf/rf[14]__0[19]} {core_instantiation/mips_i/dp/rf/rf[14]__0[20]} {core_instantiation/mips_i/dp/rf/rf[14]__0[21]} {core_instantiation/mips_i/dp/rf/rf[14]__0[22]} {core_instantiation/mips_i/dp/rf/rf[14]__0[23]} {core_instantiation/mips_i/dp/rf/rf[14]__0[24]} {core_instantiation/mips_i/dp/rf/rf[14]__0[25]} {core_instantiation/mips_i/dp/rf/rf[14]__0[26]} {core_instantiation/mips_i/dp/rf/rf[14]__0[27]} {core_instantiation/mips_i/dp/rf/rf[14]__0[28]} {core_instantiation/mips_i/dp/rf/rf[14]__0[29]} {core_instantiation/mips_i/dp/rf/rf[14]__0[30]} {core_instantiation/mips_i/dp/rf/rf[14]__0[31]}]]
create_debug_port u_ila_0 probe
set_property PROBE_TYPE DATA_AND_TRIGGER [get_debug_ports u_ila_0/probe8]
set_property port_width 32 [get_debug_ports u_ila_0/probe8]
connect_debug_port u_ila_0/probe8 [get_nets [list {core_instantiation/mips_i/dp/rf/rf[15]__0[0]} {core_instantiation/mips_i/dp/rf/rf[15]__0[1]} {core_instantiation/mips_i/dp/rf/rf[15]__0[2]} {core_instantiation/mips_i/dp/rf/rf[15]__0[3]} {core_instantiation/mips_i/dp/rf/rf[15]__0[4]} {core_instantiation/mips_i/dp/rf/rf[15]__0[5]} {core_instantiation/mips_i/dp/rf/rf[15]__0[6]} {core_instantiation/mips_i/dp/rf/rf[15]__0[7]} {core_instantiation/mips_i/dp/rf/rf[15]__0[8]} {core_instantiation/mips_i/dp/rf/rf[15]__0[9]} {core_instantiation/mips_i/dp/rf/rf[15]__0[10]} {core_instantiation/mips_i/dp/rf/rf[15]__0[11]} {core_instantiation/mips_i/dp/rf/rf[15]__0[12]} {core_instantiation/mips_i/dp/rf/rf[15]__0[13]} {core_instantiation/mips_i/dp/rf/rf[15]__0[14]} {core_instantiation/mips_i/dp/rf/rf[15]__0[15]} {core_instantiation/mips_i/dp/rf/rf[15]__0[16]} {core_instantiation/mips_i/dp/rf/rf[15]__0[17]} {core_instantiation/mips_i/dp/rf/rf[15]__0[18]} {core_instantiation/mips_i/dp/rf/rf[15]__0[19]} {core_instantiation/mips_i/dp/rf/rf[15]__0[20]} {core_instantiation/mips_i/dp/rf/rf[15]__0[21]} {core_instantiation/mips_i/dp/rf/rf[15]__0[22]} {core_instantiation/mips_i/dp/rf/rf[15]__0[23]} {core_instantiation/mips_i/dp/rf/rf[15]__0[24]} {core_instantiation/mips_i/dp/rf/rf[15]__0[25]} {core_instantiation/mips_i/dp/rf/rf[15]__0[26]} {core_instantiation/mips_i/dp/rf/rf[15]__0[27]} {core_instantiation/mips_i/dp/rf/rf[15]__0[28]} {core_instantiation/mips_i/dp/rf/rf[15]__0[29]} {core_instantiation/mips_i/dp/rf/rf[15]__0[30]} {core_instantiation/mips_i/dp/rf/rf[15]__0[31]}]]
create_debug_port u_ila_0 probe
set_property PROBE_TYPE DATA_AND_TRIGGER [get_debug_ports u_ila_0/probe9]
set_property port_width 32 [get_debug_ports u_ila_0/probe9]
connect_debug_port u_ila_0/probe9 [get_nets [list {core_instantiation/mips_i/dp/rf/rf[31]__0[0]} {core_instantiation/mips_i/dp/rf/rf[31]__0[1]} {core_instantiation/mips_i/dp/rf/rf[31]__0[2]} {core_instantiation/mips_i/dp/rf/rf[31]__0[3]} {core_instantiation/mips_i/dp/rf/rf[31]__0[4]} {core_instantiation/mips_i/dp/rf/rf[31]__0[5]} {core_instantiation/mips_i/dp/rf/rf[31]__0[6]} {core_instantiation/mips_i/dp/rf/rf[31]__0[7]} {core_instantiation/mips_i/dp/rf/rf[31]__0[8]} {core_instantiation/mips_i/dp/rf/rf[31]__0[9]} {core_instantiation/mips_i/dp/rf/rf[31]__0[10]} {core_instantiation/mips_i/dp/rf/rf[31]__0[11]} {core_instantiation/mips_i/dp/rf/rf[31]__0[12]} {core_instantiation/mips_i/dp/rf/rf[31]__0[13]} {core_instantiation/mips_i/dp/rf/rf[31]__0[14]} {core_instantiation/mips_i/dp/rf/rf[31]__0[15]} {core_instantiation/mips_i/dp/rf/rf[31]__0[16]} {core_instantiation/mips_i/dp/rf/rf[31]__0[17]} {core_instantiation/mips_i/dp/rf/rf[31]__0[18]} {core_instantiation/mips_i/dp/rf/rf[31]__0[19]} {core_instantiation/mips_i/dp/rf/rf[31]__0[20]} {core_instantiation/mips_i/dp/rf/rf[31]__0[21]} {core_instantiation/mips_i/dp/rf/rf[31]__0[22]} {core_instantiation/mips_i/dp/rf/rf[31]__0[23]} {core_instantiation/mips_i/dp/rf/rf[31]__0[24]} {core_instantiation/mips_i/dp/rf/rf[31]__0[25]} {core_instantiation/mips_i/dp/rf/rf[31]__0[26]} {core_instantiation/mips_i/dp/rf/rf[31]__0[27]} {core_instantiation/mips_i/dp/rf/rf[31]__0[28]} {core_instantiation/mips_i/dp/rf/rf[31]__0[29]} {core_instantiation/mips_i/dp/rf/rf[31]__0[30]} {core_instantiation/mips_i/dp/rf/rf[31]__0[31]}]]
create_debug_port u_ila_0 probe
set_property PROBE_TYPE DATA_AND_TRIGGER [get_debug_ports u_ila_0/probe10]
set_property port_width 32 [get_debug_ports u_ila_0/probe10]
connect_debug_port u_ila_0/probe10 [get_nets [list {core_instantiation/mips_i/dp/rf/rf[6]__0[0]} {core_instantiation/mips_i/dp/rf/rf[6]__0[1]} {core_instantiation/mips_i/dp/rf/rf[6]__0[2]} {core_instantiation/mips_i/dp/rf/rf[6]__0[3]} {core_instantiation/mips_i/dp/rf/rf[6]__0[4]} {core_instantiation/mips_i/dp/rf/rf[6]__0[5]} {core_instantiation/mips_i/dp/rf/rf[6]__0[6]} {core_instantiation/mips_i/dp/rf/rf[6]__0[7]} {core_instantiation/mips_i/dp/rf/rf[6]__0[8]} {core_instantiation/mips_i/dp/rf/rf[6]__0[9]} {core_instantiation/mips_i/dp/rf/rf[6]__0[10]} {core_instantiation/mips_i/dp/rf/rf[6]__0[11]} {core_instantiation/mips_i/dp/rf/rf[6]__0[12]} {core_instantiation/mips_i/dp/rf/rf[6]__0[13]} {core_instantiation/mips_i/dp/rf/rf[6]__0[14]} {core_instantiation/mips_i/dp/rf/rf[6]__0[15]} {core_instantiation/mips_i/dp/rf/rf[6]__0[16]} {core_instantiation/mips_i/dp/rf/rf[6]__0[17]} {core_instantiation/mips_i/dp/rf/rf[6]__0[18]} {core_instantiation/mips_i/dp/rf/rf[6]__0[19]} {core_instantiation/mips_i/dp/rf/rf[6]__0[20]} {core_instantiation/mips_i/dp/rf/rf[6]__0[21]} {core_instantiation/mips_i/dp/rf/rf[6]__0[22]} {core_instantiation/mips_i/dp/rf/rf[6]__0[23]} {core_instantiation/mips_i/dp/rf/rf[6]__0[24]} {core_instantiation/mips_i/dp/rf/rf[6]__0[25]} {core_instantiation/mips_i/dp/rf/rf[6]__0[26]} {core_instantiation/mips_i/dp/rf/rf[6]__0[27]} {core_instantiation/mips_i/dp/rf/rf[6]__0[28]} {core_instantiation/mips_i/dp/rf/rf[6]__0[29]} {core_instantiation/mips_i/dp/rf/rf[6]__0[30]} {core_instantiation/mips_i/dp/rf/rf[6]__0[31]}]]
create_debug_port u_ila_0 probe
set_property PROBE_TYPE DATA_AND_TRIGGER [get_debug_ports u_ila_0/probe11]
set_property port_width 32 [get_debug_ports u_ila_0/probe11]
connect_debug_port u_ila_0/probe11 [get_nets [list {core_instantiation/mips_i/dp/rf/rf[7]__0[0]} {core_instantiation/mips_i/dp/rf/rf[7]__0[1]} {core_instantiation/mips_i/dp/rf/rf[7]__0[2]} {core_instantiation/mips_i/dp/rf/rf[7]__0[3]} {core_instantiation/mips_i/dp/rf/rf[7]__0[4]} {core_instantiation/mips_i/dp/rf/rf[7]__0[5]} {core_instantiation/mips_i/dp/rf/rf[7]__0[6]} {core_instantiation/mips_i/dp/rf/rf[7]__0[7]} {core_instantiation/mips_i/dp/rf/rf[7]__0[8]} {core_instantiation/mips_i/dp/rf/rf[7]__0[9]} {core_instantiation/mips_i/dp/rf/rf[7]__0[10]} {core_instantiation/mips_i/dp/rf/rf[7]__0[11]} {core_instantiation/mips_i/dp/rf/rf[7]__0[12]} {core_instantiation/mips_i/dp/rf/rf[7]__0[13]} {core_instantiation/mips_i/dp/rf/rf[7]__0[14]} {core_instantiation/mips_i/dp/rf/rf[7]__0[15]} {core_instantiation/mips_i/dp/rf/rf[7]__0[16]} {core_instantiation/mips_i/dp/rf/rf[7]__0[17]} {core_instantiation/mips_i/dp/rf/rf[7]__0[18]} {core_instantiation/mips_i/dp/rf/rf[7]__0[19]} {core_instantiation/mips_i/dp/rf/rf[7]__0[20]} {core_instantiation/mips_i/dp/rf/rf[7]__0[21]} {core_instantiation/mips_i/dp/rf/rf[7]__0[22]} {core_instantiation/mips_i/dp/rf/rf[7]__0[23]} {core_instantiation/mips_i/dp/rf/rf[7]__0[24]} {core_instantiation/mips_i/dp/rf/rf[7]__0[25]} {core_instantiation/mips_i/dp/rf/rf[7]__0[26]} {core_instantiation/mips_i/dp/rf/rf[7]__0[27]} {core_instantiation/mips_i/dp/rf/rf[7]__0[28]} {core_instantiation/mips_i/dp/rf/rf[7]__0[29]} {core_instantiation/mips_i/dp/rf/rf[7]__0[30]} {core_instantiation/mips_i/dp/rf/rf[7]__0[31]}]]
create_debug_port u_ila_0 probe
set_property PROBE_TYPE DATA_AND_TRIGGER [get_debug_ports u_ila_0/probe12]
set_property port_width 32 [get_debug_ports u_ila_0/probe12]
connect_debug_port u_ila_0/probe12 [get_nets [list {core_instantiation/mips_i/dp/rf/rf[8]__0[0]} {core_instantiation/mips_i/dp/rf/rf[8]__0[1]} {core_instantiation/mips_i/dp/rf/rf[8]__0[2]} {core_instantiation/mips_i/dp/rf/rf[8]__0[3]} {core_instantiation/mips_i/dp/rf/rf[8]__0[4]} {core_instantiation/mips_i/dp/rf/rf[8]__0[5]} {core_instantiation/mips_i/dp/rf/rf[8]__0[6]} {core_instantiation/mips_i/dp/rf/rf[8]__0[7]} {core_instantiation/mips_i/dp/rf/rf[8]__0[8]} {core_instantiation/mips_i/dp/rf/rf[8]__0[9]} {core_instantiation/mips_i/dp/rf/rf[8]__0[10]} {core_instantiation/mips_i/dp/rf/rf[8]__0[11]} {core_instantiation/mips_i/dp/rf/rf[8]__0[12]} {core_instantiation/mips_i/dp/rf/rf[8]__0[13]} {core_instantiation/mips_i/dp/rf/rf[8]__0[14]} {core_instantiation/mips_i/dp/rf/rf[8]__0[15]} {core_instantiation/mips_i/dp/rf/rf[8]__0[16]} {core_instantiation/mips_i/dp/rf/rf[8]__0[17]} {core_instantiation/mips_i/dp/rf/rf[8]__0[18]} {core_instantiation/mips_i/dp/rf/rf[8]__0[19]} {core_instantiation/mips_i/dp/rf/rf[8]__0[20]} {core_instantiation/mips_i/dp/rf/rf[8]__0[21]} {core_instantiation/mips_i/dp/rf/rf[8]__0[22]} {core_instantiation/mips_i/dp/rf/rf[8]__0[23]} {core_instantiation/mips_i/dp/rf/rf[8]__0[24]} {core_instantiation/mips_i/dp/rf/rf[8]__0[25]} {core_instantiation/mips_i/dp/rf/rf[8]__0[26]} {core_instantiation/mips_i/dp/rf/rf[8]__0[27]} {core_instantiation/mips_i/dp/rf/rf[8]__0[28]} {core_instantiation/mips_i/dp/rf/rf[8]__0[29]} {core_instantiation/mips_i/dp/rf/rf[8]__0[30]} {core_instantiation/mips_i/dp/rf/rf[8]__0[31]}]]
create_debug_port u_ila_0 probe
set_property PROBE_TYPE DATA_AND_TRIGGER [get_debug_ports u_ila_0/probe13]
set_property port_width 32 [get_debug_ports u_ila_0/probe13]
connect_debug_port u_ila_0/probe13 [get_nets [list {core_instantiation/mips_i/dp/rf/rf[19]__0[0]} {core_instantiation/mips_i/dp/rf/rf[19]__0[1]} {core_instantiation/mips_i/dp/rf/rf[19]__0[2]} {core_instantiation/mips_i/dp/rf/rf[19]__0[3]} {core_instantiation/mips_i/dp/rf/rf[19]__0[4]} {core_instantiation/mips_i/dp/rf/rf[19]__0[5]} {core_instantiation/mips_i/dp/rf/rf[19]__0[6]} {core_instantiation/mips_i/dp/rf/rf[19]__0[7]} {core_instantiation/mips_i/dp/rf/rf[19]__0[8]} {core_instantiation/mips_i/dp/rf/rf[19]__0[9]} {core_instantiation/mips_i/dp/rf/rf[19]__0[10]} {core_instantiation/mips_i/dp/rf/rf[19]__0[11]} {core_instantiation/mips_i/dp/rf/rf[19]__0[12]} {core_instantiation/mips_i/dp/rf/rf[19]__0[13]} {core_instantiation/mips_i/dp/rf/rf[19]__0[14]} {core_instantiation/mips_i/dp/rf/rf[19]__0[15]} {core_instantiation/mips_i/dp/rf/rf[19]__0[16]} {core_instantiation/mips_i/dp/rf/rf[19]__0[17]} {core_instantiation/mips_i/dp/rf/rf[19]__0[18]} {core_instantiation/mips_i/dp/rf/rf[19]__0[19]} {core_instantiation/mips_i/dp/rf/rf[19]__0[20]} {core_instantiation/mips_i/dp/rf/rf[19]__0[21]} {core_instantiation/mips_i/dp/rf/rf[19]__0[22]} {core_instantiation/mips_i/dp/rf/rf[19]__0[23]} {core_instantiation/mips_i/dp/rf/rf[19]__0[24]} {core_instantiation/mips_i/dp/rf/rf[19]__0[25]} {core_instantiation/mips_i/dp/rf/rf[19]__0[26]} {core_instantiation/mips_i/dp/rf/rf[19]__0[27]} {core_instantiation/mips_i/dp/rf/rf[19]__0[28]} {core_instantiation/mips_i/dp/rf/rf[19]__0[29]} {core_instantiation/mips_i/dp/rf/rf[19]__0[30]} {core_instantiation/mips_i/dp/rf/rf[19]__0[31]}]]
create_debug_port u_ila_0 probe
set_property PROBE_TYPE DATA_AND_TRIGGER [get_debug_ports u_ila_0/probe14]
set_property port_width 32 [get_debug_ports u_ila_0/probe14]
connect_debug_port u_ila_0/probe14 [get_nets [list {core_instantiation/mips_i/dp/rf/rf[3]__0[0]} {core_instantiation/mips_i/dp/rf/rf[3]__0[1]} {core_instantiation/mips_i/dp/rf/rf[3]__0[2]} {core_instantiation/mips_i/dp/rf/rf[3]__0[3]} {core_instantiation/mips_i/dp/rf/rf[3]__0[4]} {core_instantiation/mips_i/dp/rf/rf[3]__0[5]} {core_instantiation/mips_i/dp/rf/rf[3]__0[6]} {core_instantiation/mips_i/dp/rf/rf[3]__0[7]} {core_instantiation/mips_i/dp/rf/rf[3]__0[8]} {core_instantiation/mips_i/dp/rf/rf[3]__0[9]} {core_instantiation/mips_i/dp/rf/rf[3]__0[10]} {core_instantiation/mips_i/dp/rf/rf[3]__0[11]} {core_instantiation/mips_i/dp/rf/rf[3]__0[12]} {core_instantiation/mips_i/dp/rf/rf[3]__0[13]} {core_instantiation/mips_i/dp/rf/rf[3]__0[14]} {core_instantiation/mips_i/dp/rf/rf[3]__0[15]} {core_instantiation/mips_i/dp/rf/rf[3]__0[16]} {core_instantiation/mips_i/dp/rf/rf[3]__0[17]} {core_instantiation/mips_i/dp/rf/rf[3]__0[18]} {core_instantiation/mips_i/dp/rf/rf[3]__0[19]} {core_instantiation/mips_i/dp/rf/rf[3]__0[20]} {core_instantiation/mips_i/dp/rf/rf[3]__0[21]} {core_instantiation/mips_i/dp/rf/rf[3]__0[22]} {core_instantiation/mips_i/dp/rf/rf[3]__0[23]} {core_instantiation/mips_i/dp/rf/rf[3]__0[24]} {core_instantiation/mips_i/dp/rf/rf[3]__0[25]} {core_instantiation/mips_i/dp/rf/rf[3]__0[26]} {core_instantiation/mips_i/dp/rf/rf[3]__0[27]} {core_instantiation/mips_i/dp/rf/rf[3]__0[28]} {core_instantiation/mips_i/dp/rf/rf[3]__0[29]} {core_instantiation/mips_i/dp/rf/rf[3]__0[30]} {core_instantiation/mips_i/dp/rf/rf[3]__0[31]}]]
create_debug_port u_ila_0 probe
set_property PROBE_TYPE DATA_AND_TRIGGER [get_debug_ports u_ila_0/probe15]
set_property port_width 32 [get_debug_ports u_ila_0/probe15]
connect_debug_port u_ila_0/probe15 [get_nets [list {core_instantiation/mips_i/dp/rf/rf[9]__0[0]} {core_instantiation/mips_i/dp/rf/rf[9]__0[1]} {core_instantiation/mips_i/dp/rf/rf[9]__0[2]} {core_instantiation/mips_i/dp/rf/rf[9]__0[3]} {core_instantiation/mips_i/dp/rf/rf[9]__0[4]} {core_instantiation/mips_i/dp/rf/rf[9]__0[5]} {core_instantiation/mips_i/dp/rf/rf[9]__0[6]} {core_instantiation/mips_i/dp/rf/rf[9]__0[7]} {core_instantiation/mips_i/dp/rf/rf[9]__0[8]} {core_instantiation/mips_i/dp/rf/rf[9]__0[9]} {core_instantiation/mips_i/dp/rf/rf[9]__0[10]} {core_instantiation/mips_i/dp/rf/rf[9]__0[11]} {core_instantiation/mips_i/dp/rf/rf[9]__0[12]} {core_instantiation/mips_i/dp/rf/rf[9]__0[13]} {core_instantiation/mips_i/dp/rf/rf[9]__0[14]} {core_instantiation/mips_i/dp/rf/rf[9]__0[15]} {core_instantiation/mips_i/dp/rf/rf[9]__0[16]} {core_instantiation/mips_i/dp/rf/rf[9]__0[17]} {core_instantiation/mips_i/dp/rf/rf[9]__0[18]} {core_instantiation/mips_i/dp/rf/rf[9]__0[19]} {core_instantiation/mips_i/dp/rf/rf[9]__0[20]} {core_instantiation/mips_i/dp/rf/rf[9]__0[21]} {core_instantiation/mips_i/dp/rf/rf[9]__0[22]} {core_instantiation/mips_i/dp/rf/rf[9]__0[23]} {core_instantiation/mips_i/dp/rf/rf[9]__0[24]} {core_instantiation/mips_i/dp/rf/rf[9]__0[25]} {core_instantiation/mips_i/dp/rf/rf[9]__0[26]} {core_instantiation/mips_i/dp/rf/rf[9]__0[27]} {core_instantiation/mips_i/dp/rf/rf[9]__0[28]} {core_instantiation/mips_i/dp/rf/rf[9]__0[29]} {core_instantiation/mips_i/dp/rf/rf[9]__0[30]} {core_instantiation/mips_i/dp/rf/rf[9]__0[31]}]]
create_debug_port u_ila_0 probe
set_property PROBE_TYPE DATA_AND_TRIGGER [get_debug_ports u_ila_0/probe16]
set_property port_width 32 [get_debug_ports u_ila_0/probe16]
connect_debug_port u_ila_0/probe16 [get_nets [list {core_instantiation/mips_i/dp/rf/rf[23]__0[0]} {core_instantiation/mips_i/dp/rf/rf[23]__0[1]} {core_instantiation/mips_i/dp/rf/rf[23]__0[2]} {core_instantiation/mips_i/dp/rf/rf[23]__0[3]} {core_instantiation/mips_i/dp/rf/rf[23]__0[4]} {core_instantiation/mips_i/dp/rf/rf[23]__0[5]} {core_instantiation/mips_i/dp/rf/rf[23]__0[6]} {core_instantiation/mips_i/dp/rf/rf[23]__0[7]} {core_instantiation/mips_i/dp/rf/rf[23]__0[8]} {core_instantiation/mips_i/dp/rf/rf[23]__0[9]} {core_instantiation/mips_i/dp/rf/rf[23]__0[10]} {core_instantiation/mips_i/dp/rf/rf[23]__0[11]} {core_instantiation/mips_i/dp/rf/rf[23]__0[12]} {core_instantiation/mips_i/dp/rf/rf[23]__0[13]} {core_instantiation/mips_i/dp/rf/rf[23]__0[14]} {core_instantiation/mips_i/dp/rf/rf[23]__0[15]} {core_instantiation/mips_i/dp/rf/rf[23]__0[16]} {core_instantiation/mips_i/dp/rf/rf[23]__0[17]} {core_instantiation/mips_i/dp/rf/rf[23]__0[18]} {core_instantiation/mips_i/dp/rf/rf[23]__0[19]} {core_instantiation/mips_i/dp/rf/rf[23]__0[20]} {core_instantiation/mips_i/dp/rf/rf[23]__0[21]} {core_instantiation/mips_i/dp/rf/rf[23]__0[22]} {core_instantiation/mips_i/dp/rf/rf[23]__0[23]} {core_instantiation/mips_i/dp/rf/rf[23]__0[24]} {core_instantiation/mips_i/dp/rf/rf[23]__0[25]} {core_instantiation/mips_i/dp/rf/rf[23]__0[26]} {core_instantiation/mips_i/dp/rf/rf[23]__0[27]} {core_instantiation/mips_i/dp/rf/rf[23]__0[28]} {core_instantiation/mips_i/dp/rf/rf[23]__0[29]} {core_instantiation/mips_i/dp/rf/rf[23]__0[30]} {core_instantiation/mips_i/dp/rf/rf[23]__0[31]}]]
create_debug_port u_ila_0 probe
set_property PROBE_TYPE DATA_AND_TRIGGER [get_debug_ports u_ila_0/probe17]
set_property port_width 32 [get_debug_ports u_ila_0/probe17]
connect_debug_port u_ila_0/probe17 [get_nets [list {core_instantiation/mips_i/dp/rf/rf[26]__0[0]} {core_instantiation/mips_i/dp/rf/rf[26]__0[1]} {core_instantiation/mips_i/dp/rf/rf[26]__0[2]} {core_instantiation/mips_i/dp/rf/rf[26]__0[3]} {core_instantiation/mips_i/dp/rf/rf[26]__0[4]} {core_instantiation/mips_i/dp/rf/rf[26]__0[5]} {core_instantiation/mips_i/dp/rf/rf[26]__0[6]} {core_instantiation/mips_i/dp/rf/rf[26]__0[7]} {core_instantiation/mips_i/dp/rf/rf[26]__0[8]} {core_instantiation/mips_i/dp/rf/rf[26]__0[9]} {core_instantiation/mips_i/dp/rf/rf[26]__0[10]} {core_instantiation/mips_i/dp/rf/rf[26]__0[11]} {core_instantiation/mips_i/dp/rf/rf[26]__0[12]} {core_instantiation/mips_i/dp/rf/rf[26]__0[13]} {core_instantiation/mips_i/dp/rf/rf[26]__0[14]} {core_instantiation/mips_i/dp/rf/rf[26]__0[15]} {core_instantiation/mips_i/dp/rf/rf[26]__0[16]} {core_instantiation/mips_i/dp/rf/rf[26]__0[17]} {core_instantiation/mips_i/dp/rf/rf[26]__0[18]} {core_instantiation/mips_i/dp/rf/rf[26]__0[19]} {core_instantiation/mips_i/dp/rf/rf[26]__0[20]} {core_instantiation/mips_i/dp/rf/rf[26]__0[21]} {core_instantiation/mips_i/dp/rf/rf[26]__0[22]} {core_instantiation/mips_i/dp/rf/rf[26]__0[23]} {core_instantiation/mips_i/dp/rf/rf[26]__0[24]} {core_instantiation/mips_i/dp/rf/rf[26]__0[25]} {core_instantiation/mips_i/dp/rf/rf[26]__0[26]} {core_instantiation/mips_i/dp/rf/rf[26]__0[27]} {core_instantiation/mips_i/dp/rf/rf[26]__0[28]} {core_instantiation/mips_i/dp/rf/rf[26]__0[29]} {core_instantiation/mips_i/dp/rf/rf[26]__0[30]} {core_instantiation/mips_i/dp/rf/rf[26]__0[31]}]]
create_debug_port u_ila_0 probe
set_property PROBE_TYPE DATA_AND_TRIGGER [get_debug_ports u_ila_0/probe18]
set_property port_width 32 [get_debug_ports u_ila_0/probe18]
connect_debug_port u_ila_0/probe18 [get_nets [list {core_instantiation/mips_i/dp/rf/rf[22]__0[0]} {core_instantiation/mips_i/dp/rf/rf[22]__0[1]} {core_instantiation/mips_i/dp/rf/rf[22]__0[2]} {core_instantiation/mips_i/dp/rf/rf[22]__0[3]} {core_instantiation/mips_i/dp/rf/rf[22]__0[4]} {core_instantiation/mips_i/dp/rf/rf[22]__0[5]} {core_instantiation/mips_i/dp/rf/rf[22]__0[6]} {core_instantiation/mips_i/dp/rf/rf[22]__0[7]} {core_instantiation/mips_i/dp/rf/rf[22]__0[8]} {core_instantiation/mips_i/dp/rf/rf[22]__0[9]} {core_instantiation/mips_i/dp/rf/rf[22]__0[10]} {core_instantiation/mips_i/dp/rf/rf[22]__0[11]} {core_instantiation/mips_i/dp/rf/rf[22]__0[12]} {core_instantiation/mips_i/dp/rf/rf[22]__0[13]} {core_instantiation/mips_i/dp/rf/rf[22]__0[14]} {core_instantiation/mips_i/dp/rf/rf[22]__0[15]} {core_instantiation/mips_i/dp/rf/rf[22]__0[16]} {core_instantiation/mips_i/dp/rf/rf[22]__0[17]} {core_instantiation/mips_i/dp/rf/rf[22]__0[18]} {core_instantiation/mips_i/dp/rf/rf[22]__0[19]} {core_instantiation/mips_i/dp/rf/rf[22]__0[20]} {core_instantiation/mips_i/dp/rf/rf[22]__0[21]} {core_instantiation/mips_i/dp/rf/rf[22]__0[22]} {core_instantiation/mips_i/dp/rf/rf[22]__0[23]} {core_instantiation/mips_i/dp/rf/rf[22]__0[24]} {core_instantiation/mips_i/dp/rf/rf[22]__0[25]} {core_instantiation/mips_i/dp/rf/rf[22]__0[26]} {core_instantiation/mips_i/dp/rf/rf[22]__0[27]} {core_instantiation/mips_i/dp/rf/rf[22]__0[28]} {core_instantiation/mips_i/dp/rf/rf[22]__0[29]} {core_instantiation/mips_i/dp/rf/rf[22]__0[30]} {core_instantiation/mips_i/dp/rf/rf[22]__0[31]}]]
create_debug_port u_ila_0 probe
set_property PROBE_TYPE DATA_AND_TRIGGER [get_debug_ports u_ila_0/probe19]
set_property port_width 32 [get_debug_ports u_ila_0/probe19]
connect_debug_port u_ila_0/probe19 [get_nets [list {core_instantiation/mips_i/dp/rf/rf[4]__0[0]} {core_instantiation/mips_i/dp/rf/rf[4]__0[1]} {core_instantiation/mips_i/dp/rf/rf[4]__0[2]} {core_instantiation/mips_i/dp/rf/rf[4]__0[3]} {core_instantiation/mips_i/dp/rf/rf[4]__0[4]} {core_instantiation/mips_i/dp/rf/rf[4]__0[5]} {core_instantiation/mips_i/dp/rf/rf[4]__0[6]} {core_instantiation/mips_i/dp/rf/rf[4]__0[7]} {core_instantiation/mips_i/dp/rf/rf[4]__0[8]} {core_instantiation/mips_i/dp/rf/rf[4]__0[9]} {core_instantiation/mips_i/dp/rf/rf[4]__0[10]} {core_instantiation/mips_i/dp/rf/rf[4]__0[11]} {core_instantiation/mips_i/dp/rf/rf[4]__0[12]} {core_instantiation/mips_i/dp/rf/rf[4]__0[13]} {core_instantiation/mips_i/dp/rf/rf[4]__0[14]} {core_instantiation/mips_i/dp/rf/rf[4]__0[15]} {core_instantiation/mips_i/dp/rf/rf[4]__0[16]} {core_instantiation/mips_i/dp/rf/rf[4]__0[17]} {core_instantiation/mips_i/dp/rf/rf[4]__0[18]} {core_instantiation/mips_i/dp/rf/rf[4]__0[19]} {core_instantiation/mips_i/dp/rf/rf[4]__0[20]} {core_instantiation/mips_i/dp/rf/rf[4]__0[21]} {core_instantiation/mips_i/dp/rf/rf[4]__0[22]} {core_instantiation/mips_i/dp/rf/rf[4]__0[23]} {core_instantiation/mips_i/dp/rf/rf[4]__0[24]} {core_instantiation/mips_i/dp/rf/rf[4]__0[25]} {core_instantiation/mips_i/dp/rf/rf[4]__0[26]} {core_instantiation/mips_i/dp/rf/rf[4]__0[27]} {core_instantiation/mips_i/dp/rf/rf[4]__0[28]} {core_instantiation/mips_i/dp/rf/rf[4]__0[29]} {core_instantiation/mips_i/dp/rf/rf[4]__0[30]} {core_instantiation/mips_i/dp/rf/rf[4]__0[31]}]]
create_debug_port u_ila_0 probe
set_property PROBE_TYPE DATA_AND_TRIGGER [get_debug_ports u_ila_0/probe20]
set_property port_width 32 [get_debug_ports u_ila_0/probe20]
connect_debug_port u_ila_0/probe20 [get_nets [list {core_instantiation/mips_i/dp/rf/rf[1]__0[0]} {core_instantiation/mips_i/dp/rf/rf[1]__0[1]} {core_instantiation/mips_i/dp/rf/rf[1]__0[2]} {core_instantiation/mips_i/dp/rf/rf[1]__0[3]} {core_instantiation/mips_i/dp/rf/rf[1]__0[4]} {core_instantiation/mips_i/dp/rf/rf[1]__0[5]} {core_instantiation/mips_i/dp/rf/rf[1]__0[6]} {core_instantiation/mips_i/dp/rf/rf[1]__0[7]} {core_instantiation/mips_i/dp/rf/rf[1]__0[8]} {core_instantiation/mips_i/dp/rf/rf[1]__0[9]} {core_instantiation/mips_i/dp/rf/rf[1]__0[10]} {core_instantiation/mips_i/dp/rf/rf[1]__0[11]} {core_instantiation/mips_i/dp/rf/rf[1]__0[12]} {core_instantiation/mips_i/dp/rf/rf[1]__0[13]} {core_instantiation/mips_i/dp/rf/rf[1]__0[14]} {core_instantiation/mips_i/dp/rf/rf[1]__0[15]} {core_instantiation/mips_i/dp/rf/rf[1]__0[16]} {core_instantiation/mips_i/dp/rf/rf[1]__0[17]} {core_instantiation/mips_i/dp/rf/rf[1]__0[18]} {core_instantiation/mips_i/dp/rf/rf[1]__0[19]} {core_instantiation/mips_i/dp/rf/rf[1]__0[20]} {core_instantiation/mips_i/dp/rf/rf[1]__0[21]} {core_instantiation/mips_i/dp/rf/rf[1]__0[22]} {core_instantiation/mips_i/dp/rf/rf[1]__0[23]} {core_instantiation/mips_i/dp/rf/rf[1]__0[24]} {core_instantiation/mips_i/dp/rf/rf[1]__0[25]} {core_instantiation/mips_i/dp/rf/rf[1]__0[26]} {core_instantiation/mips_i/dp/rf/rf[1]__0[27]} {core_instantiation/mips_i/dp/rf/rf[1]__0[28]} {core_instantiation/mips_i/dp/rf/rf[1]__0[29]} {core_instantiation/mips_i/dp/rf/rf[1]__0[30]} {core_instantiation/mips_i/dp/rf/rf[1]__0[31]}]]
create_debug_port u_ila_0 probe
set_property PROBE_TYPE DATA_AND_TRIGGER [get_debug_ports u_ila_0/probe21]
set_property port_width 32 [get_debug_ports u_ila_0/probe21]
connect_debug_port u_ila_0/probe21 [get_nets [list {core_instantiation/mips_i/dp/rf/rf[24]__0[0]} {core_instantiation/mips_i/dp/rf/rf[24]__0[1]} {core_instantiation/mips_i/dp/rf/rf[24]__0[2]} {core_instantiation/mips_i/dp/rf/rf[24]__0[3]} {core_instantiation/mips_i/dp/rf/rf[24]__0[4]} {core_instantiation/mips_i/dp/rf/rf[24]__0[5]} {core_instantiation/mips_i/dp/rf/rf[24]__0[6]} {core_instantiation/mips_i/dp/rf/rf[24]__0[7]} {core_instantiation/mips_i/dp/rf/rf[24]__0[8]} {core_instantiation/mips_i/dp/rf/rf[24]__0[9]} {core_instantiation/mips_i/dp/rf/rf[24]__0[10]} {core_instantiation/mips_i/dp/rf/rf[24]__0[11]} {core_instantiation/mips_i/dp/rf/rf[24]__0[12]} {core_instantiation/mips_i/dp/rf/rf[24]__0[13]} {core_instantiation/mips_i/dp/rf/rf[24]__0[14]} {core_instantiation/mips_i/dp/rf/rf[24]__0[15]} {core_instantiation/mips_i/dp/rf/rf[24]__0[16]} {core_instantiation/mips_i/dp/rf/rf[24]__0[17]} {core_instantiation/mips_i/dp/rf/rf[24]__0[18]} {core_instantiation/mips_i/dp/rf/rf[24]__0[19]} {core_instantiation/mips_i/dp/rf/rf[24]__0[20]} {core_instantiation/mips_i/dp/rf/rf[24]__0[21]} {core_instantiation/mips_i/dp/rf/rf[24]__0[22]} {core_instantiation/mips_i/dp/rf/rf[24]__0[23]} {core_instantiation/mips_i/dp/rf/rf[24]__0[24]} {core_instantiation/mips_i/dp/rf/rf[24]__0[25]} {core_instantiation/mips_i/dp/rf/rf[24]__0[26]} {core_instantiation/mips_i/dp/rf/rf[24]__0[27]} {core_instantiation/mips_i/dp/rf/rf[24]__0[28]} {core_instantiation/mips_i/dp/rf/rf[24]__0[29]} {core_instantiation/mips_i/dp/rf/rf[24]__0[30]} {core_instantiation/mips_i/dp/rf/rf[24]__0[31]}]]
create_debug_port u_ila_0 probe
set_property PROBE_TYPE DATA_AND_TRIGGER [get_debug_ports u_ila_0/probe22]
set_property port_width 32 [get_debug_ports u_ila_0/probe22]
connect_debug_port u_ila_0/probe22 [get_nets [list {core_instantiation/mips_i/dp/rf/rf[20]__0[0]} {core_instantiation/mips_i/dp/rf/rf[20]__0[1]} {core_instantiation/mips_i/dp/rf/rf[20]__0[2]} {core_instantiation/mips_i/dp/rf/rf[20]__0[3]} {core_instantiation/mips_i/dp/rf/rf[20]__0[4]} {core_instantiation/mips_i/dp/rf/rf[20]__0[5]} {core_instantiation/mips_i/dp/rf/rf[20]__0[6]} {core_instantiation/mips_i/dp/rf/rf[20]__0[7]} {core_instantiation/mips_i/dp/rf/rf[20]__0[8]} {core_instantiation/mips_i/dp/rf/rf[20]__0[9]} {core_instantiation/mips_i/dp/rf/rf[20]__0[10]} {core_instantiation/mips_i/dp/rf/rf[20]__0[11]} {core_instantiation/mips_i/dp/rf/rf[20]__0[12]} {core_instantiation/mips_i/dp/rf/rf[20]__0[13]} {core_instantiation/mips_i/dp/rf/rf[20]__0[14]} {core_instantiation/mips_i/dp/rf/rf[20]__0[15]} {core_instantiation/mips_i/dp/rf/rf[20]__0[16]} {core_instantiation/mips_i/dp/rf/rf[20]__0[17]} {core_instantiation/mips_i/dp/rf/rf[20]__0[18]} {core_instantiation/mips_i/dp/rf/rf[20]__0[19]} {core_instantiation/mips_i/dp/rf/rf[20]__0[20]} {core_instantiation/mips_i/dp/rf/rf[20]__0[21]} {core_instantiation/mips_i/dp/rf/rf[20]__0[22]} {core_instantiation/mips_i/dp/rf/rf[20]__0[23]} {core_instantiation/mips_i/dp/rf/rf[20]__0[24]} {core_instantiation/mips_i/dp/rf/rf[20]__0[25]} {core_instantiation/mips_i/dp/rf/rf[20]__0[26]} {core_instantiation/mips_i/dp/rf/rf[20]__0[27]} {core_instantiation/mips_i/dp/rf/rf[20]__0[28]} {core_instantiation/mips_i/dp/rf/rf[20]__0[29]} {core_instantiation/mips_i/dp/rf/rf[20]__0[30]} {core_instantiation/mips_i/dp/rf/rf[20]__0[31]}]]
create_debug_port u_ila_0 probe
set_property PROBE_TYPE DATA_AND_TRIGGER [get_debug_ports u_ila_0/probe23]
set_property port_width 32 [get_debug_ports u_ila_0/probe23]
connect_debug_port u_ila_0/probe23 [get_nets [list {core_instantiation/mips_i/dp/rf/rf[21]__0[0]} {core_instantiation/mips_i/dp/rf/rf[21]__0[1]} {core_instantiation/mips_i/dp/rf/rf[21]__0[2]} {core_instantiation/mips_i/dp/rf/rf[21]__0[3]} {core_instantiation/mips_i/dp/rf/rf[21]__0[4]} {core_instantiation/mips_i/dp/rf/rf[21]__0[5]} {core_instantiation/mips_i/dp/rf/rf[21]__0[6]} {core_instantiation/mips_i/dp/rf/rf[21]__0[7]} {core_instantiation/mips_i/dp/rf/rf[21]__0[8]} {core_instantiation/mips_i/dp/rf/rf[21]__0[9]} {core_instantiation/mips_i/dp/rf/rf[21]__0[10]} {core_instantiation/mips_i/dp/rf/rf[21]__0[11]} {core_instantiation/mips_i/dp/rf/rf[21]__0[12]} {core_instantiation/mips_i/dp/rf/rf[21]__0[13]} {core_instantiation/mips_i/dp/rf/rf[21]__0[14]} {core_instantiation/mips_i/dp/rf/rf[21]__0[15]} {core_instantiation/mips_i/dp/rf/rf[21]__0[16]} {core_instantiation/mips_i/dp/rf/rf[21]__0[17]} {core_instantiation/mips_i/dp/rf/rf[21]__0[18]} {core_instantiation/mips_i/dp/rf/rf[21]__0[19]} {core_instantiation/mips_i/dp/rf/rf[21]__0[20]} {core_instantiation/mips_i/dp/rf/rf[21]__0[21]} {core_instantiation/mips_i/dp/rf/rf[21]__0[22]} {core_instantiation/mips_i/dp/rf/rf[21]__0[23]} {core_instantiation/mips_i/dp/rf/rf[21]__0[24]} {core_instantiation/mips_i/dp/rf/rf[21]__0[25]} {core_instantiation/mips_i/dp/rf/rf[21]__0[26]} {core_instantiation/mips_i/dp/rf/rf[21]__0[27]} {core_instantiation/mips_i/dp/rf/rf[21]__0[28]} {core_instantiation/mips_i/dp/rf/rf[21]__0[29]} {core_instantiation/mips_i/dp/rf/rf[21]__0[30]} {core_instantiation/mips_i/dp/rf/rf[21]__0[31]}]]
create_debug_port u_ila_0 probe
set_property PROBE_TYPE DATA_AND_TRIGGER [get_debug_ports u_ila_0/probe24]
set_property port_width 32 [get_debug_ports u_ila_0/probe24]
connect_debug_port u_ila_0/probe24 [get_nets [list {core_instantiation/mips_i/dp/rf/rf[25]__0[0]} {core_instantiation/mips_i/dp/rf/rf[25]__0[1]} {core_instantiation/mips_i/dp/rf/rf[25]__0[2]} {core_instantiation/mips_i/dp/rf/rf[25]__0[3]} {core_instantiation/mips_i/dp/rf/rf[25]__0[4]} {core_instantiation/mips_i/dp/rf/rf[25]__0[5]} {core_instantiation/mips_i/dp/rf/rf[25]__0[6]} {core_instantiation/mips_i/dp/rf/rf[25]__0[7]} {core_instantiation/mips_i/dp/rf/rf[25]__0[8]} {core_instantiation/mips_i/dp/rf/rf[25]__0[9]} {core_instantiation/mips_i/dp/rf/rf[25]__0[10]} {core_instantiation/mips_i/dp/rf/rf[25]__0[11]} {core_instantiation/mips_i/dp/rf/rf[25]__0[12]} {core_instantiation/mips_i/dp/rf/rf[25]__0[13]} {core_instantiation/mips_i/dp/rf/rf[25]__0[14]} {core_instantiation/mips_i/dp/rf/rf[25]__0[15]} {core_instantiation/mips_i/dp/rf/rf[25]__0[16]} {core_instantiation/mips_i/dp/rf/rf[25]__0[17]} {core_instantiation/mips_i/dp/rf/rf[25]__0[18]} {core_instantiation/mips_i/dp/rf/rf[25]__0[19]} {core_instantiation/mips_i/dp/rf/rf[25]__0[20]} {core_instantiation/mips_i/dp/rf/rf[25]__0[21]} {core_instantiation/mips_i/dp/rf/rf[25]__0[22]} {core_instantiation/mips_i/dp/rf/rf[25]__0[23]} {core_instantiation/mips_i/dp/rf/rf[25]__0[24]} {core_instantiation/mips_i/dp/rf/rf[25]__0[25]} {core_instantiation/mips_i/dp/rf/rf[25]__0[26]} {core_instantiation/mips_i/dp/rf/rf[25]__0[27]} {core_instantiation/mips_i/dp/rf/rf[25]__0[28]} {core_instantiation/mips_i/dp/rf/rf[25]__0[29]} {core_instantiation/mips_i/dp/rf/rf[25]__0[30]} {core_instantiation/mips_i/dp/rf/rf[25]__0[31]}]]
create_debug_port u_ila_0 probe
set_property PROBE_TYPE DATA_AND_TRIGGER [get_debug_ports u_ila_0/probe25]
set_property port_width 32 [get_debug_ports u_ila_0/probe25]
connect_debug_port u_ila_0/probe25 [get_nets [list {core_instantiation/mips_i/dp/rf/rf[27]__0[0]} {core_instantiation/mips_i/dp/rf/rf[27]__0[1]} {core_instantiation/mips_i/dp/rf/rf[27]__0[2]} {core_instantiation/mips_i/dp/rf/rf[27]__0[3]} {core_instantiation/mips_i/dp/rf/rf[27]__0[4]} {core_instantiation/mips_i/dp/rf/rf[27]__0[5]} {core_instantiation/mips_i/dp/rf/rf[27]__0[6]} {core_instantiation/mips_i/dp/rf/rf[27]__0[7]} {core_instantiation/mips_i/dp/rf/rf[27]__0[8]} {core_instantiation/mips_i/dp/rf/rf[27]__0[9]} {core_instantiation/mips_i/dp/rf/rf[27]__0[10]} {core_instantiation/mips_i/dp/rf/rf[27]__0[11]} {core_instantiation/mips_i/dp/rf/rf[27]__0[12]} {core_instantiation/mips_i/dp/rf/rf[27]__0[13]} {core_instantiation/mips_i/dp/rf/rf[27]__0[14]} {core_instantiation/mips_i/dp/rf/rf[27]__0[15]} {core_instantiation/mips_i/dp/rf/rf[27]__0[16]} {core_instantiation/mips_i/dp/rf/rf[27]__0[17]} {core_instantiation/mips_i/dp/rf/rf[27]__0[18]} {core_instantiation/mips_i/dp/rf/rf[27]__0[19]} {core_instantiation/mips_i/dp/rf/rf[27]__0[20]} {core_instantiation/mips_i/dp/rf/rf[27]__0[21]} {core_instantiation/mips_i/dp/rf/rf[27]__0[22]} {core_instantiation/mips_i/dp/rf/rf[27]__0[23]} {core_instantiation/mips_i/dp/rf/rf[27]__0[24]} {core_instantiation/mips_i/dp/rf/rf[27]__0[25]} {core_instantiation/mips_i/dp/rf/rf[27]__0[26]} {core_instantiation/mips_i/dp/rf/rf[27]__0[27]} {core_instantiation/mips_i/dp/rf/rf[27]__0[28]} {core_instantiation/mips_i/dp/rf/rf[27]__0[29]} {core_instantiation/mips_i/dp/rf/rf[27]__0[30]} {core_instantiation/mips_i/dp/rf/rf[27]__0[31]}]]
create_debug_port u_ila_0 probe
set_property PROBE_TYPE DATA_AND_TRIGGER [get_debug_ports u_ila_0/probe26]
set_property port_width 32 [get_debug_ports u_ila_0/probe26]
connect_debug_port u_ila_0/probe26 [get_nets [list {core_instantiation/mips_i/dp/rf/rf[28]__0[0]} {core_instantiation/mips_i/dp/rf/rf[28]__0[1]} {core_instantiation/mips_i/dp/rf/rf[28]__0[2]} {core_instantiation/mips_i/dp/rf/rf[28]__0[3]} {core_instantiation/mips_i/dp/rf/rf[28]__0[4]} {core_instantiation/mips_i/dp/rf/rf[28]__0[5]} {core_instantiation/mips_i/dp/rf/rf[28]__0[6]} {core_instantiation/mips_i/dp/rf/rf[28]__0[7]} {core_instantiation/mips_i/dp/rf/rf[28]__0[8]} {core_instantiation/mips_i/dp/rf/rf[28]__0[9]} {core_instantiation/mips_i/dp/rf/rf[28]__0[10]} {core_instantiation/mips_i/dp/rf/rf[28]__0[11]} {core_instantiation/mips_i/dp/rf/rf[28]__0[12]} {core_instantiation/mips_i/dp/rf/rf[28]__0[13]} {core_instantiation/mips_i/dp/rf/rf[28]__0[14]} {core_instantiation/mips_i/dp/rf/rf[28]__0[15]} {core_instantiation/mips_i/dp/rf/rf[28]__0[16]} {core_instantiation/mips_i/dp/rf/rf[28]__0[17]} {core_instantiation/mips_i/dp/rf/rf[28]__0[18]} {core_instantiation/mips_i/dp/rf/rf[28]__0[19]} {core_instantiation/mips_i/dp/rf/rf[28]__0[20]} {core_instantiation/mips_i/dp/rf/rf[28]__0[21]} {core_instantiation/mips_i/dp/rf/rf[28]__0[22]} {core_instantiation/mips_i/dp/rf/rf[28]__0[23]} {core_instantiation/mips_i/dp/rf/rf[28]__0[24]} {core_instantiation/mips_i/dp/rf/rf[28]__0[25]} {core_instantiation/mips_i/dp/rf/rf[28]__0[26]} {core_instantiation/mips_i/dp/rf/rf[28]__0[27]} {core_instantiation/mips_i/dp/rf/rf[28]__0[28]} {core_instantiation/mips_i/dp/rf/rf[28]__0[29]} {core_instantiation/mips_i/dp/rf/rf[28]__0[30]} {core_instantiation/mips_i/dp/rf/rf[28]__0[31]}]]
create_debug_port u_ila_0 probe
set_property PROBE_TYPE DATA_AND_TRIGGER [get_debug_ports u_ila_0/probe27]
set_property port_width 32 [get_debug_ports u_ila_0/probe27]
connect_debug_port u_ila_0/probe27 [get_nets [list {core_instantiation/mips_i/dp/rf/rf[29]__0[0]} {core_instantiation/mips_i/dp/rf/rf[29]__0[1]} {core_instantiation/mips_i/dp/rf/rf[29]__0[2]} {core_instantiation/mips_i/dp/rf/rf[29]__0[3]} {core_instantiation/mips_i/dp/rf/rf[29]__0[4]} {core_instantiation/mips_i/dp/rf/rf[29]__0[5]} {core_instantiation/mips_i/dp/rf/rf[29]__0[6]} {core_instantiation/mips_i/dp/rf/rf[29]__0[7]} {core_instantiation/mips_i/dp/rf/rf[29]__0[8]} {core_instantiation/mips_i/dp/rf/rf[29]__0[9]} {core_instantiation/mips_i/dp/rf/rf[29]__0[10]} {core_instantiation/mips_i/dp/rf/rf[29]__0[11]} {core_instantiation/mips_i/dp/rf/rf[29]__0[12]} {core_instantiation/mips_i/dp/rf/rf[29]__0[13]} {core_instantiation/mips_i/dp/rf/rf[29]__0[14]} {core_instantiation/mips_i/dp/rf/rf[29]__0[15]} {core_instantiation/mips_i/dp/rf/rf[29]__0[16]} {core_instantiation/mips_i/dp/rf/rf[29]__0[17]} {core_instantiation/mips_i/dp/rf/rf[29]__0[18]} {core_instantiation/mips_i/dp/rf/rf[29]__0[19]} {core_instantiation/mips_i/dp/rf/rf[29]__0[20]} {core_instantiation/mips_i/dp/rf/rf[29]__0[21]} {core_instantiation/mips_i/dp/rf/rf[29]__0[22]} {core_instantiation/mips_i/dp/rf/rf[29]__0[23]} {core_instantiation/mips_i/dp/rf/rf[29]__0[24]} {core_instantiation/mips_i/dp/rf/rf[29]__0[25]} {core_instantiation/mips_i/dp/rf/rf[29]__0[26]} {core_instantiation/mips_i/dp/rf/rf[29]__0[27]} {core_instantiation/mips_i/dp/rf/rf[29]__0[28]} {core_instantiation/mips_i/dp/rf/rf[29]__0[29]} {core_instantiation/mips_i/dp/rf/rf[29]__0[30]} {core_instantiation/mips_i/dp/rf/rf[29]__0[31]}]]
create_debug_port u_ila_0 probe
set_property PROBE_TYPE DATA_AND_TRIGGER [get_debug_ports u_ila_0/probe28]
set_property port_width 32 [get_debug_ports u_ila_0/probe28]
connect_debug_port u_ila_0/probe28 [get_nets [list {core_instantiation/mips_i/dp/rf/rf[5]__0[0]} {core_instantiation/mips_i/dp/rf/rf[5]__0[1]} {core_instantiation/mips_i/dp/rf/rf[5]__0[2]} {core_instantiation/mips_i/dp/rf/rf[5]__0[3]} {core_instantiation/mips_i/dp/rf/rf[5]__0[4]} {core_instantiation/mips_i/dp/rf/rf[5]__0[5]} {core_instantiation/mips_i/dp/rf/rf[5]__0[6]} {core_instantiation/mips_i/dp/rf/rf[5]__0[7]} {core_instantiation/mips_i/dp/rf/rf[5]__0[8]} {core_instantiation/mips_i/dp/rf/rf[5]__0[9]} {core_instantiation/mips_i/dp/rf/rf[5]__0[10]} {core_instantiation/mips_i/dp/rf/rf[5]__0[11]} {core_instantiation/mips_i/dp/rf/rf[5]__0[12]} {core_instantiation/mips_i/dp/rf/rf[5]__0[13]} {core_instantiation/mips_i/dp/rf/rf[5]__0[14]} {core_instantiation/mips_i/dp/rf/rf[5]__0[15]} {core_instantiation/mips_i/dp/rf/rf[5]__0[16]} {core_instantiation/mips_i/dp/rf/rf[5]__0[17]} {core_instantiation/mips_i/dp/rf/rf[5]__0[18]} {core_instantiation/mips_i/dp/rf/rf[5]__0[19]} {core_instantiation/mips_i/dp/rf/rf[5]__0[20]} {core_instantiation/mips_i/dp/rf/rf[5]__0[21]} {core_instantiation/mips_i/dp/rf/rf[5]__0[22]} {core_instantiation/mips_i/dp/rf/rf[5]__0[23]} {core_instantiation/mips_i/dp/rf/rf[5]__0[24]} {core_instantiation/mips_i/dp/rf/rf[5]__0[25]} {core_instantiation/mips_i/dp/rf/rf[5]__0[26]} {core_instantiation/mips_i/dp/rf/rf[5]__0[27]} {core_instantiation/mips_i/dp/rf/rf[5]__0[28]} {core_instantiation/mips_i/dp/rf/rf[5]__0[29]} {core_instantiation/mips_i/dp/rf/rf[5]__0[30]} {core_instantiation/mips_i/dp/rf/rf[5]__0[31]}]]
create_debug_port u_ila_0 probe
set_property PROBE_TYPE DATA_AND_TRIGGER [get_debug_ports u_ila_0/probe29]
set_property port_width 32 [get_debug_ports u_ila_0/probe29]
connect_debug_port u_ila_0/probe29 [get_nets [list {core_instantiation/mips_i/dp/rf/rf[30]__0[0]} {core_instantiation/mips_i/dp/rf/rf[30]__0[1]} {core_instantiation/mips_i/dp/rf/rf[30]__0[2]} {core_instantiation/mips_i/dp/rf/rf[30]__0[3]} {core_instantiation/mips_i/dp/rf/rf[30]__0[4]} {core_instantiation/mips_i/dp/rf/rf[30]__0[5]} {core_instantiation/mips_i/dp/rf/rf[30]__0[6]} {core_instantiation/mips_i/dp/rf/rf[30]__0[7]} {core_instantiation/mips_i/dp/rf/rf[30]__0[8]} {core_instantiation/mips_i/dp/rf/rf[30]__0[9]} {core_instantiation/mips_i/dp/rf/rf[30]__0[10]} {core_instantiation/mips_i/dp/rf/rf[30]__0[11]} {core_instantiation/mips_i/dp/rf/rf[30]__0[12]} {core_instantiation/mips_i/dp/rf/rf[30]__0[13]} {core_instantiation/mips_i/dp/rf/rf[30]__0[14]} {core_instantiation/mips_i/dp/rf/rf[30]__0[15]} {core_instantiation/mips_i/dp/rf/rf[30]__0[16]} {core_instantiation/mips_i/dp/rf/rf[30]__0[17]} {core_instantiation/mips_i/dp/rf/rf[30]__0[18]} {core_instantiation/mips_i/dp/rf/rf[30]__0[19]} {core_instantiation/mips_i/dp/rf/rf[30]__0[20]} {core_instantiation/mips_i/dp/rf/rf[30]__0[21]} {core_instantiation/mips_i/dp/rf/rf[30]__0[22]} {core_instantiation/mips_i/dp/rf/rf[30]__0[23]} {core_instantiation/mips_i/dp/rf/rf[30]__0[24]} {core_instantiation/mips_i/dp/rf/rf[30]__0[25]} {core_instantiation/mips_i/dp/rf/rf[30]__0[26]} {core_instantiation/mips_i/dp/rf/rf[30]__0[27]} {core_instantiation/mips_i/dp/rf/rf[30]__0[28]} {core_instantiation/mips_i/dp/rf/rf[30]__0[29]} {core_instantiation/mips_i/dp/rf/rf[30]__0[30]} {core_instantiation/mips_i/dp/rf/rf[30]__0[31]}]]
create_debug_port u_ila_0 probe
set_property PROBE_TYPE DATA_AND_TRIGGER [get_debug_ports u_ila_0/probe30]
set_property port_width 32 [get_debug_ports u_ila_0/probe30]
connect_debug_port u_ila_0/probe30 [get_nets [list {core_instantiation/mips_i/dp/rf/rf[18]__0[0]} {core_instantiation/mips_i/dp/rf/rf[18]__0[1]} {core_instantiation/mips_i/dp/rf/rf[18]__0[2]} {core_instantiation/mips_i/dp/rf/rf[18]__0[3]} {core_instantiation/mips_i/dp/rf/rf[18]__0[4]} {core_instantiation/mips_i/dp/rf/rf[18]__0[5]} {core_instantiation/mips_i/dp/rf/rf[18]__0[6]} {core_instantiation/mips_i/dp/rf/rf[18]__0[7]} {core_instantiation/mips_i/dp/rf/rf[18]__0[8]} {core_instantiation/mips_i/dp/rf/rf[18]__0[9]} {core_instantiation/mips_i/dp/rf/rf[18]__0[10]} {core_instantiation/mips_i/dp/rf/rf[18]__0[11]} {core_instantiation/mips_i/dp/rf/rf[18]__0[12]} {core_instantiation/mips_i/dp/rf/rf[18]__0[13]} {core_instantiation/mips_i/dp/rf/rf[18]__0[14]} {core_instantiation/mips_i/dp/rf/rf[18]__0[15]} {core_instantiation/mips_i/dp/rf/rf[18]__0[16]} {core_instantiation/mips_i/dp/rf/rf[18]__0[17]} {core_instantiation/mips_i/dp/rf/rf[18]__0[18]} {core_instantiation/mips_i/dp/rf/rf[18]__0[19]} {core_instantiation/mips_i/dp/rf/rf[18]__0[20]} {core_instantiation/mips_i/dp/rf/rf[18]__0[21]} {core_instantiation/mips_i/dp/rf/rf[18]__0[22]} {core_instantiation/mips_i/dp/rf/rf[18]__0[23]} {core_instantiation/mips_i/dp/rf/rf[18]__0[24]} {core_instantiation/mips_i/dp/rf/rf[18]__0[25]} {core_instantiation/mips_i/dp/rf/rf[18]__0[26]} {core_instantiation/mips_i/dp/rf/rf[18]__0[27]} {core_instantiation/mips_i/dp/rf/rf[18]__0[28]} {core_instantiation/mips_i/dp/rf/rf[18]__0[29]} {core_instantiation/mips_i/dp/rf/rf[18]__0[30]} {core_instantiation/mips_i/dp/rf/rf[18]__0[31]}]]
create_debug_port u_ila_0 probe
set_property PROBE_TYPE DATA_AND_TRIGGER [get_debug_ports u_ila_0/probe31]
set_property port_width 32 [get_debug_ports u_ila_0/probe31]
connect_debug_port u_ila_0/probe31 [get_nets [list {core_instantiation/mips_i/dp/rf/rf[2]__0[0]} {core_instantiation/mips_i/dp/rf/rf[2]__0[1]} {core_instantiation/mips_i/dp/rf/rf[2]__0[2]} {core_instantiation/mips_i/dp/rf/rf[2]__0[3]} {core_instantiation/mips_i/dp/rf/rf[2]__0[4]} {core_instantiation/mips_i/dp/rf/rf[2]__0[5]} {core_instantiation/mips_i/dp/rf/rf[2]__0[6]} {core_instantiation/mips_i/dp/rf/rf[2]__0[7]} {core_instantiation/mips_i/dp/rf/rf[2]__0[8]} {core_instantiation/mips_i/dp/rf/rf[2]__0[9]} {core_instantiation/mips_i/dp/rf/rf[2]__0[10]} {core_instantiation/mips_i/dp/rf/rf[2]__0[11]} {core_instantiation/mips_i/dp/rf/rf[2]__0[12]} {core_instantiation/mips_i/dp/rf/rf[2]__0[13]} {core_instantiation/mips_i/dp/rf/rf[2]__0[14]} {core_instantiation/mips_i/dp/rf/rf[2]__0[15]} {core_instantiation/mips_i/dp/rf/rf[2]__0[16]} {core_instantiation/mips_i/dp/rf/rf[2]__0[17]} {core_instantiation/mips_i/dp/rf/rf[2]__0[18]} {core_instantiation/mips_i/dp/rf/rf[2]__0[19]} {core_instantiation/mips_i/dp/rf/rf[2]__0[20]} {core_instantiation/mips_i/dp/rf/rf[2]__0[21]} {core_instantiation/mips_i/dp/rf/rf[2]__0[22]} {core_instantiation/mips_i/dp/rf/rf[2]__0[23]} {core_instantiation/mips_i/dp/rf/rf[2]__0[24]} {core_instantiation/mips_i/dp/rf/rf[2]__0[25]} {core_instantiation/mips_i/dp/rf/rf[2]__0[26]} {core_instantiation/mips_i/dp/rf/rf[2]__0[27]} {core_instantiation/mips_i/dp/rf/rf[2]__0[28]} {core_instantiation/mips_i/dp/rf/rf[2]__0[29]} {core_instantiation/mips_i/dp/rf/rf[2]__0[30]} {core_instantiation/mips_i/dp/rf/rf[2]__0[31]}]]
create_debug_port u_ila_0 probe
set_property PROBE_TYPE DATA_AND_TRIGGER [get_debug_ports u_ila_0/probe32]
set_property port_width 32 [get_debug_ports u_ila_0/probe32]
connect_debug_port u_ila_0/probe32 [get_nets [list {core_instantiation/dataadr[0]} {core_instantiation/dataadr[1]} {core_instantiation/dataadr[2]} {core_instantiation/dataadr[3]} {core_instantiation/dataadr[4]} {core_instantiation/dataadr[5]} {core_instantiation/dataadr[6]} {core_instantiation/dataadr[7]} {core_instantiation/dataadr[8]} {core_instantiation/dataadr[9]} {core_instantiation/dataadr[10]} {core_instantiation/dataadr[11]} {core_instantiation/dataadr[12]} {core_instantiation/dataadr[13]} {core_instantiation/dataadr[14]} {core_instantiation/dataadr[15]} {core_instantiation/dataadr[16]} {core_instantiation/dataadr[17]} {core_instantiation/dataadr[18]} {core_instantiation/dataadr[19]} {core_instantiation/dataadr[20]} {core_instantiation/dataadr[21]} {core_instantiation/dataadr[22]} {core_instantiation/dataadr[23]} {core_instantiation/dataadr[24]} {core_instantiation/dataadr[25]} {core_instantiation/dataadr[26]} {core_instantiation/dataadr[27]} {core_instantiation/dataadr[28]} {core_instantiation/dataadr[29]} {core_instantiation/dataadr[30]} {core_instantiation/dataadr[31]}]]
create_debug_port u_ila_0 probe
set_property PROBE_TYPE DATA_AND_TRIGGER [get_debug_ports u_ila_0/probe33]
set_property port_width 32 [get_debug_ports u_ila_0/probe33]
connect_debug_port u_ila_0/probe33 [get_nets [list {core_instantiation/readdata[0]} {core_instantiation/readdata[1]} {core_instantiation/readdata[2]} {core_instantiation/readdata[3]} {core_instantiation/readdata[4]} {core_instantiation/readdata[5]} {core_instantiation/readdata[6]} {core_instantiation/readdata[7]} {core_instantiation/readdata[8]} {core_instantiation/readdata[9]} {core_instantiation/readdata[10]} {core_instantiation/readdata[11]} {core_instantiation/readdata[12]} {core_instantiation/readdata[13]} {core_instantiation/readdata[14]} {core_instantiation/readdata[15]} {core_instantiation/readdata[16]} {core_instantiation/readdata[17]} {core_instantiation/readdata[18]} {core_instantiation/readdata[19]} {core_instantiation/readdata[20]} {core_instantiation/readdata[21]} {core_instantiation/readdata[22]} {core_instantiation/readdata[23]} {core_instantiation/readdata[24]} {core_instantiation/readdata[25]} {core_instantiation/readdata[26]} {core_instantiation/readdata[27]} {core_instantiation/readdata[28]} {core_instantiation/readdata[29]} {core_instantiation/readdata[30]} {core_instantiation/readdata[31]}]]
create_debug_port u_ila_0 probe
set_property PROBE_TYPE DATA_AND_TRIGGER [get_debug_ports u_ila_0/probe34]
set_property port_width 32 [get_debug_ports u_ila_0/probe34]
connect_debug_port u_ila_0/probe34 [get_nets [list {core_instantiation/writedata[0]} {core_instantiation/writedata[1]} {core_instantiation/writedata[2]} {core_instantiation/writedata[3]} {core_instantiation/writedata[4]} {core_instantiation/writedata[5]} {core_instantiation/writedata[6]} {core_instantiation/writedata[7]} {core_instantiation/writedata[8]} {core_instantiation/writedata[9]} {core_instantiation/writedata[10]} {core_instantiation/writedata[11]} {core_instantiation/writedata[12]} {core_instantiation/writedata[13]} {core_instantiation/writedata[14]} {core_instantiation/writedata[15]} {core_instantiation/writedata[16]} {core_instantiation/writedata[17]} {core_instantiation/writedata[18]} {core_instantiation/writedata[19]} {core_instantiation/writedata[20]} {core_instantiation/writedata[21]} {core_instantiation/writedata[22]} {core_instantiation/writedata[23]} {core_instantiation/writedata[24]} {core_instantiation/writedata[25]} {core_instantiation/writedata[26]} {core_instantiation/writedata[27]} {core_instantiation/writedata[28]} {core_instantiation/writedata[29]} {core_instantiation/writedata[30]} {core_instantiation/writedata[31]}]]
create_debug_port u_ila_0 probe
set_property PROBE_TYPE DATA_AND_TRIGGER [get_debug_ports u_ila_0/probe35]
set_property port_width 32 [get_debug_ports u_ila_0/probe35]
connect_debug_port u_ila_0/probe35 [get_nets [list {instr[0]} {instr[1]} {instr[2]} {instr[3]} {instr[4]} {instr[5]} {instr[6]} {instr[7]} {instr[8]} {instr[9]} {instr[10]} {instr[11]} {instr[12]} {instr[13]} {instr[14]} {instr[15]} {instr[16]} {instr[17]} {instr[18]} {instr[19]} {instr[20]} {instr[21]} {instr[22]} {instr[23]} {instr[24]} {instr[25]} {instr[26]} {instr[27]} {instr[28]} {instr[29]} {instr[30]} {instr[31]}]]
create_debug_port u_ila_0 probe
set_property PROBE_TYPE DATA_AND_TRIGGER [get_debug_ports u_ila_0/probe36]
set_property port_width 32 [get_debug_ports u_ila_0/probe36]
connect_debug_port u_ila_0/probe36 [get_nets [list {core_instantiation/pc[0]} {core_instantiation/pc[1]} {core_instantiation/pc[2]} {core_instantiation/pc[3]} {core_instantiation/pc[4]} {core_instantiation/pc[5]} {core_instantiation/pc[6]} {core_instantiation/pc[7]} {core_instantiation/pc[8]} {core_instantiation/pc[9]} {core_instantiation/pc[10]} {core_instantiation/pc[11]} {core_instantiation/pc[12]} {core_instantiation/pc[13]} {core_instantiation/pc[14]} {core_instantiation/pc[15]} {core_instantiation/pc[16]} {core_instantiation/pc[17]} {core_instantiation/pc[18]} {core_instantiation/pc[19]} {core_instantiation/pc[20]} {core_instantiation/pc[21]} {core_instantiation/pc[22]} {core_instantiation/pc[23]} {core_instantiation/pc[24]} {core_instantiation/pc[25]} {core_instantiation/pc[26]} {core_instantiation/pc[27]} {core_instantiation/pc[28]} {core_instantiation/pc[29]} {core_instantiation/pc[30]} {core_instantiation/pc[31]}]]
create_debug_port u_ila_0 probe
set_property PROBE_TYPE DATA_AND_TRIGGER [get_debug_ports u_ila_0/probe37]
set_property port_width 32 [get_debug_ports u_ila_0/probe37]
connect_debug_port u_ila_0/probe37 [get_nets [list {core_instantiation/instr[0]} {core_instantiation/instr[1]} {core_instantiation/instr[2]} {core_instantiation/instr[3]} {core_instantiation/instr[4]} {core_instantiation/instr[5]} {core_instantiation/instr[6]} {core_instantiation/instr[7]} {core_instantiation/instr[8]} {core_instantiation/instr[9]} {core_instantiation/instr[10]} {core_instantiation/instr[11]} {core_instantiation/instr[12]} {core_instantiation/instr[13]} {core_instantiation/instr[14]} {core_instantiation/instr[15]} {core_instantiation/instr[16]} {core_instantiation/instr[17]} {core_instantiation/instr[18]} {core_instantiation/instr[19]} {core_instantiation/instr[20]} {core_instantiation/instr[21]} {core_instantiation/instr[22]} {core_instantiation/instr[23]} {core_instantiation/instr[24]} {core_instantiation/instr[25]} {core_instantiation/instr[26]} {core_instantiation/instr[27]} {core_instantiation/instr[28]} {core_instantiation/instr[29]} {core_instantiation/instr[30]} {core_instantiation/instr[31]}]]
create_debug_port u_ila_0 probe
set_property PROBE_TYPE DATA_AND_TRIGGER [get_debug_ports u_ila_0/probe38]
set_property port_width 2 [get_debug_ports u_ila_0/probe38]
connect_debug_port u_ila_0/probe38 [get_nets [list {state_next[0]} {state_next[1]}]]
create_debug_port u_ila_0 probe
set_property PROBE_TYPE DATA_AND_TRIGGER [get_debug_ports u_ila_0/probe39]
set_property port_width 2 [get_debug_ports u_ila_0/probe39]
connect_debug_port u_ila_0/probe39 [get_nets [list {state[0]} {state[1]}]]
create_debug_port u_ila_0 probe
set_property PROBE_TYPE DATA_AND_TRIGGER [get_debug_ports u_ila_0/probe40]
set_property port_width 1 [get_debug_ports u_ila_0/probe40]
connect_debug_port u_ila_0/probe40 [get_nets [list core_instantiation/memwrite]]
create_debug_port u_ila_0 probe
set_property PROBE_TYPE DATA_AND_TRIGGER [get_debug_ports u_ila_0/probe41]
set_property port_width 1 [get_debug_ports u_ila_0/probe41]
connect_debug_port u_ila_0/probe41 [get_nets [list start_pulse]]
create_debug_port u_ila_0 probe
set_property PROBE_TYPE DATA_AND_TRIGGER [get_debug_ports u_ila_0/probe42]
set_property port_width 1 [get_debug_ports u_ila_0/probe42]
connect_debug_port u_ila_0/probe42 [get_nets [list step_en]]
create_debug_port u_ila_0 probe
set_property PROBE_TYPE DATA_AND_TRIGGER [get_debug_ports u_ila_0/probe43]
set_property port_width 1 [get_debug_ports u_ila_0/probe43]
connect_debug_port u_ila_0/probe43 [get_nets [list step_pulse]]
set_property C_CLK_INPUT_FREQ_HZ 300000000 [get_debug_cores dbg_hub]
set_property C_ENABLE_CLK_DIVIDER false [get_debug_cores dbg_hub]
set_property C_USER_SCAN_CHAIN 1 [get_debug_cores dbg_hub]
connect_debug_port dbg_hub/clk [get_nets clk_50]
