# This file is automatically generated.
# It contains project source information necessary for synthesis and implementation.

# IP: c:/Users/Monster/Xilinx/Vivado_Projects/CS401_LAB4/CS401_LAB4.srcs/sources_1/ip/clk_wiz_100_to_50/clk_wiz_100_to_50.xci
# IP: The module: 'clk_wiz_100_to_50' is the root of the design. Do not add the DONT_TOUCH constraint.

# XDC: c:/Users/Monster/Xilinx/Vivado_Projects/CS401_LAB4/CS401_LAB4.gen/sources_1/ip/clk_wiz_100_to_50/clk_wiz_100_to_50_board.xdc
# XDC: The top module name and the constraint reference have the same name: 'clk_wiz_100_to_50'. Do not add the DONT_TOUCH constraint.
set_property KEEP_HIERARCHY SOFT [get_cells inst -quiet] -quiet

# XDC: c:/Users/Monster/Xilinx/Vivado_Projects/CS401_LAB4/CS401_LAB4.gen/sources_1/ip/clk_wiz_100_to_50/clk_wiz_100_to_50.xdc
# XDC: The top module name and the constraint reference have the same name: 'clk_wiz_100_to_50'. Do not add the DONT_TOUCH constraint.
#dup# set_property KEEP_HIERARCHY SOFT [get_cells inst -quiet] -quiet

# XDC: c:/Users/Monster/Xilinx/Vivado_Projects/CS401_LAB4/CS401_LAB4.gen/sources_1/ip/clk_wiz_100_to_50/clk_wiz_100_to_50_ooc.xdc
# XDC: The top module name and the constraint reference have the same name: 'clk_wiz_100_to_50'. Do not add the DONT_TOUCH constraint.
#dup# set_property KEEP_HIERARCHY SOFT [get_cells inst -quiet] -quiet

# IP: c:/Users/Monster/Xilinx/Vivado_Projects/CS401_LAB4/CS401_LAB4.srcs/sources_1/ip/clk_wiz_100_to_50/clk_wiz_100_to_50.xci
# IP: The module: 'clk_wiz_100_to_50' is the root of the design. Do not add the DONT_TOUCH constraint.

# XDC: c:/Users/Monster/Xilinx/Vivado_Projects/CS401_LAB4/CS401_LAB4.gen/sources_1/ip/clk_wiz_100_to_50/clk_wiz_100_to_50_board.xdc
# XDC: The top module name and the constraint reference have the same name: 'clk_wiz_100_to_50'. Do not add the DONT_TOUCH constraint.
#dup# set_property KEEP_HIERARCHY SOFT [get_cells inst -quiet] -quiet

# XDC: c:/Users/Monster/Xilinx/Vivado_Projects/CS401_LAB4/CS401_LAB4.gen/sources_1/ip/clk_wiz_100_to_50/clk_wiz_100_to_50.xdc
# XDC: The top module name and the constraint reference have the same name: 'clk_wiz_100_to_50'. Do not add the DONT_TOUCH constraint.
#dup# set_property KEEP_HIERARCHY SOFT [get_cells inst -quiet] -quiet

# XDC: c:/Users/Monster/Xilinx/Vivado_Projects/CS401_LAB4/CS401_LAB4.gen/sources_1/ip/clk_wiz_100_to_50/clk_wiz_100_to_50_ooc.xdc
# XDC: The top module name and the constraint reference have the same name: 'clk_wiz_100_to_50'. Do not add the DONT_TOUCH constraint.
#dup# set_property KEEP_HIERARCHY SOFT [get_cells inst -quiet] -quiet
